#!/usr/bin/env python3
"""
Generates a tree-style file listing of the repo and inserts it into
README.md between two marker comments. Safe to re-run: if the markers
already exist, the section between them is replaced rather than a new
one being appended each time.

Usage:
    python3 generate_file_list.py            # assumes repo root is cwd
    python3 generate_file_list.py /path/to/repo
"""
import sys
from pathlib import Path

START_MARKER = "<!-- FILE_LIST:START -->"
END_MARKER = "<!-- FILE_LIST:END -->"

# Directories to skip entirely - build output, caches, and IDE/VCS metadata
# rather than anything you'd want to show me in a "here's my repo" listing.
EXCLUDE_DIRS = {
    ".git", ".gradle", ".idea", ".vscode",
    "build", "out", "bin", "run", "runs",
    "__pycache__", "node_modules",
}


def build_tree(root: Path) -> str:
    lines = [f"{root.name}/"]

    def walk(dir_path: Path, prefix: str):
        try:
            entries = sorted(
                (e for e in dir_path.iterdir()
                 if e.name not in EXCLUDE_DIRS and not e.name.startswith(".")),
                key=lambda e: (e.is_file(), e.name.lower())
            )
        except PermissionError:
            return

        for i, entry in enumerate(entries):
            is_last = (i == len(entries) - 1)
            connector = "└── " if is_last else "├── "
            label = entry.name + "/" if entry.is_dir() else entry.name
            lines.append(f"{prefix}{connector}{label}")
            if entry.is_dir():
                extension = "    " if is_last else "│   "
                walk(entry, prefix + extension)

    walk(root, "")
    return "\n".join(lines)


def build_section(root: Path) -> str:
    tree_text = build_tree(root)
    return (
        f"{START_MARKER}\n"
        f"## Repository file listing\n\n"
        f"_Auto-generated by generate_file_list.py - do not edit by hand, "
        f"just re-run the script._\n\n"
        f"```\n{tree_text}\n```\n"
        f"{END_MARKER}"
    )


def update_readme(repo_root: Path):
    readme_path = repo_root / "README.md"
    if not readme_path.exists():
        print(f"No README.md found at {readme_path}", file=sys.stderr)
        sys.exit(1)

    content = readme_path.read_text(encoding="utf-8")
    section = build_section(repo_root)

    if START_MARKER in content and END_MARKER in content:
        before = content.split(START_MARKER)[0].rstrip()
        after = content.split(END_MARKER)[1].lstrip()
        new_content = f"{before}\n\n{section}\n\n{after}".rstrip() + "\n"
        print("Replaced existing file listing.")
    else:
        new_content = content.rstrip() + "\n\n" + section + "\n"
        print("Appended new file listing (no existing markers found).")

    readme_path.write_text(new_content, encoding="utf-8")
    print(f"Wrote {readme_path}")


if __name__ == "__main__":
    root_arg = sys.argv[1] if len(sys.argv) > 1 else "."
    update_readme(Path(root_arg).resolve())