modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC BY-NC 4.0"

[[mods]]
modId = "horsegenetics"
version = "0.0.1"
displayName = "Horse Genetics"
description = "Genetics-based coat generation for horses, starting with extension/agouti and bay leg patterning."

[[dependencies.horsegenetics]]
    modId = "neoforge"
    type = "required"
    versionRange = "[26.1.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.horsegenetics]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.26.1,1.27)"
    ordering = "NONE"
    side = "BOTH"
