package com.example.horsegenetics.neoforge.compat;

import com.example.horsegenetics.neoforge.HorseGenetics;
import net.minecraft.SharedConstants;
import net.minecraft.network.chat.Component;
import net.minecraft.server.packs.PackLocationInfo;
import net.minecraft.server.packs.PackSelectionConfig;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.PathPackResources;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackCompatibility;
import net.minecraft.server.packs.repository.PackSource;
import net.minecraft.world.flag.FeatureFlagSet;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.loading.FMLPaths;
import net.neoforged.neoforge.event.AddPackFindersEvent;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.Map;
import java.util.Optional;
import java.util.TreeMap;
import java.util.stream.Stream;

/**
 * <b>The content this mod makes for other mods' materials</b>, written to disk
 * once and then served to the game as an ordinary pack.
 *
 * <p>Everything in it is derived from {@link ModdedMaterials}: a double gate per
 * modded wood, a horse armour per modded ingot, and the models, blockstates,
 * recipes, loot tables, lang and trades that go with them.
 *
 * <h2>Why a pack on disk and not resources in memory</h2>
 * Three reasons, in the order they mattered.
 * <ul>
 *   <li><b>It is the owner's own suggestion, made honest.</b> The fallback
 *       offered was a one-time tool you run in the Minecraft directory that
 *       "builds patches". This is that, minus the running it: same folder, same
 *       inspectable files, generated by the mod at the moment it knows what to
 *       generate.</li>
 *   <li><b>Silent failure is the enemy.</b> A generated gate that does not draw
 *       is a purple-and-black cube with no error anywhere. With the pack on
 *       disk the model that failed can be opened and read, which is the
 *       difference between a five-minute fix and an afternoon.</li>
 *   <li><b>It is a datapack as well as a resource pack.</b> Recipes, loot tables
 *       and villager trades are server data; a client-side-only answer would
 *       have given the gates no recipe and the armour no trade.</li>
 * </ul>
 *
 * <h2>Generate once, check on every launch</h2>
 * The folder carries the {@link ModdedMaterials#fingerprint()} it was built
 * from. On every launch the fingerprint is recomputed from the mods actually
 * present; if it matches, nothing is written. Add or remove a wood-adding mod
 * and it will not match, and the folder is rebuilt from scratch - <b>wiped</b>
 * first, rather than written over, because a stale file for a mod that is gone
 * is exactly the kind of thing that then loads and fails for a reason nobody can
 * find.
 *
 * <h2>No pack.mcmeta, on purpose</h2>
 * The pack is built with {@link Pack#Pack} and an explicit
 * {@link Pack.Metadata} rather than through {@code readMetaAndCreate}, so
 * nothing has to write a pack format number and then be wrong about it the next
 * time the format moves. The {@code README.txt} in the folder is for the reader,
 * not for the game.
 */
@EventBusSubscriber(modid = HorseGenetics.MOD_ID)
public final class GeneratedPack {

    /** Beside the breeds, the genes and the two config files - see ModBreedSpecs. */
    private static final String FOLDER = "phc/generated";
    private static final String FINGERPRINT_FILE = ".fingerprint";

    private static Path root;
    private static boolean built;

    private GeneratedPack() {
    }

    public static Path root() {
        return root;
    }

    /**
     * Build the folder if what is in it is not what this pack of mods needs.
     *
     * <p>Called from {@link #addPackFinders} rather than from the mod
     * constructor, and the difference matters: by the time a pack repository is
     * being assembled <b>every mod's items exist</b>, which is what lets
     * {@link ModdedMaterials#itemExists} throw out the recipe ingredients that
     * were only ever a declaration in somebody's tag file.
     *
     * <p><b>Items existing is not the same as items being readable</b>, and the
     * difference is a crash. Every item's data components - its armour value,
     * its rarity, its stack size - are bound during the first datapack load,
     * which is after this. Anything here that asks another mod's item a question
     * about itself gets {@code Components not bound yet} and takes mod loading
     * down with it; see the note on {@code ModdedArmour}.
     *
     * <p>Fires once. The event comes round twice - once per pack type - and a
     * resource reload brings it round again.
     */
    static void build() {
        if (built) {
            return;
        }
        built = true;
        root = FMLPaths.GAMEDIR.get().resolve(FOLDER);
        String want = ModdedMaterials.fingerprint();

        if (want.equals(readFingerprint())) {
            HorseGenetics.LOGGER.info("compat: generated pack is current ({})", want);
            return;
        }

        Map<String, byte[]> files = new TreeMap<>();
        // One lang file between them, because there is only one path the game
        // reads and the second writer to it would otherwise silently replace
        // the first's keys rather than adding to them.
        com.google.gson.JsonObject lang = new com.google.gson.JsonObject();
        GeneratedGates.emit(files, lang);
        GeneratedArmour.emit(files, lang);
        GeneratedCarts.emit(files, lang);
        GeneratedJumps.emit(files, lang);
        if (!lang.isEmpty()) {
            GeneratedGates.put(files,
                    "assets/" + HorseGenetics.MOD_ID + "/lang/en_us.json", lang);
        }

        if (files.isEmpty()) {
            // No modded materials at all - the overwhelmingly common case. Leave
            // no folder behind rather than an empty one nobody can explain.
            wipe();
            HorseGenetics.LOGGER.info("compat: nothing to generate");
            return;
        }

        try {
            wipe();
            Files.createDirectories(root);
            for (Map.Entry<String, byte[]> file : files.entrySet()) {
                Path out = root.resolve(file.getKey());
                Files.createDirectories(out.getParent());
                Files.write(out, file.getValue());
            }
            Files.writeString(root.resolve("README.txt"), readme(), StandardCharsets.UTF_8);
            Files.writeString(root.resolve(FINGERPRINT_FILE), want, StandardCharsets.UTF_8);
            HorseGenetics.LOGGER.info("compat: generated {} files for {} woods and {} metals ({})",
                    files.size(), ModdedMaterials.woods().size(), ModdedMaterials.metals().size(), want);
        } catch (IOException failed) {
            // The game is still perfectly playable without any of this, so a
            // read-only game directory costs the compat content and nothing
            // more. Loud, because the symptom otherwise is "my gates vanished".
            HorseGenetics.LOGGER.error("compat: could not write {} - no modded gates or armour this run",
                    root, failed);
        }
    }

    private static String readFingerprint() {
        try {
            Path file = root.resolve(FINGERPRINT_FILE);
            return Files.isRegularFile(file) ? Files.readString(file, StandardCharsets.UTF_8).trim() : "";
        } catch (IOException unreadable) {
            return "";
        }
    }

    private static void wipe() {
        if (root == null || !Files.isDirectory(root)) {
            return;
        }
        try (Stream<Path> walk = Files.walk(root)) {
            walk.sorted(Comparator.reverseOrder()).forEach(path -> {
                try {
                    Files.deleteIfExists(path);
                } catch (IOException ignored) {
                    // Left behind; the write below will overwrite what it needs.
                }
            });
        } catch (IOException ignored) {
            // Same.
        }
    }

    /**
     * Both pack types. Recipes and trades are server data and the models are
     * client resources, so the same folder is offered to both repositories and
     * each takes the half it understands.
     *
     * <p>{@code alwaysActive} because the player never chose to install this and
     * must not have to go and switch it on - and {@code Position.TOP} so a
     * generated file wins over a shipped one of the same name, which is what
     * lets the generated Metalsmith trade tiers replace the shipped ones rather
     * than fight them.
     */
    @SubscribeEvent
    static void addPackFinders(AddPackFindersEvent event) {
        build();
        if (root == null || !Files.isDirectory(root)) {
            return;
        }
        PackType type = event.getPackType();
        PackLocationInfo location = new PackLocationInfo(
                HorseGenetics.MOD_ID + "_generated",
                Component.literal("Horse Genetics - generated compatibility"),
                PackSource.BUILT_IN,
                Optional.empty());
        // Two abstract methods, so not a lambda. Both open the same folder:
        // there are no overlays here for the "full" form to layer on.
        Pack.ResourcesSupplier resources = new Pack.ResourcesSupplier() {
            @Override
            public net.minecraft.server.packs.PackResources openPrimary(PackLocationInfo info) {
                return new PathPackResources(info, root);
            }

            @Override
            public net.minecraft.server.packs.PackResources openFull(PackLocationInfo info, Pack.Metadata meta) {
                return new PathPackResources(info, root);
            }
        };
        Pack.Metadata metadata = new Pack.Metadata(
                Component.literal("Double gates and horse armour for other mods' materials"),
                PackCompatibility.COMPATIBLE,
                FeatureFlagSet.of(),
                java.util.List.of(),
                true); // hidden: it is machinery, not a pack the player picked
        Pack pack = new Pack(location, resources, metadata,
                new PackSelectionConfig(true, Pack.Position.TOP, false));
        event.addRepositorySource(consumer -> consumer.accept(pack));
        HorseGenetics.LOGGER.debug("compat: offered the generated pack to the {} repository", type);
    }

    private static String readme() {
        return """
                Horse Genetics - generated compatibility content
                ===============================================

                EVERYTHING IN THIS FOLDER IS GENERATED AND WILL BE DELETED.

                It is written when the mod starts and finds woods or metals that
                other mods added: a double fence gate for every modded wood, and
                a horse armour for every modded ingot or gem, with the models,
                blockstates, recipes, loot tables, language keys and villager
                trades that go with them.

                The file called .fingerprint records which mods it was built for.
                On every launch that is recomputed; if it still matches, nothing
                here is touched. If you add or remove a mod it will not match,
                and this whole folder is deleted and written again.

                So: do not edit anything in here, and do not put anything of your
                own in here. Both will be thrown away the next time your mod list
                changes. If a generated file is WRONG, that is worth knowing
                about - read it, and report what it says.

                Built against Minecraft %s.
                """.formatted(SharedConstants.getCurrentVersion().name());
    }
}
