package com.example.horsegenetics.common.breed;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * <b>Which vanilla biome a modded overworld biome is standing in for.</b> A
 * breed names the biomes it lives in, and it names them in vanilla's vocabulary
 * - {@code minecraft:plains}, {@code minecraft:taiga}. A world generated by
 * Terralith or Regions Unexplored is mostly <i>their</i> biomes, so without
 * this a pack with either had wild herds only in the patches of vanilla terrain
 * left between them, and none at all in {@code terralith:steppe} - a biome that
 * is plains in every way a horse cares about.
 *
 * <p>This table says so once, here, rather than in every breed file. A breed
 * that names {@code minecraft:plains} is a breed of every biome listed below as
 * plains-like, which means:
 * <ul>
 *   <li>a modded biome gets the <i>whole</i> pool of its analogue, not a
 *       hand-picked two or three, so Terralith country reads like vanilla
 *       country;</li>
 *   <li>a drop-in breed and a breed moved in {@code breed-spawning.toml} bring
 *       their modded biomes with them - nothing is restated per breed, and an
 *       install whose toml was written before this still gets it;</li>
 *   <li>a breed may still name a modded biome directly, and that works exactly as
 *       it always did. The two are a union.</li>
 * </ul>
 *
 * <p><b>Scope: the overworld surface only</b> (owner, 2026-09-30). Cave biomes
 * are left out because a horse needs lit grass there and none spawns; Nether,
 * End, Aether and Undergarden biomes are left out because their floors are not
 * grass and giving them breeds is a design call of its own ({@code spawn_ground}
 * is the mechanism if it is ever made). Oceans map to beach: vanilla puts no
 * horse in an ocean, but a grassy islet in one is where the island ponies live.
 *
 * <p>The ids come from the biome JSONs in the jars themselves (Terralith 2.6.1,
 * Regions Unexplored 0.7.0, Integrated Dynamics, EvilCraft), not from a wiki,
 * and each was matched on temperature, rainfall and what the biome already
 * spawns. A biome of a mod that is not installed is simply never asked about.
 */
public final class BiomeAnalogues {

    private static final Map<String, List<String>> ANALOGUES = new HashMap<>();

    static {
        // ---- Terralith --------------------------------------------------------
        t("alpha_islands", "plains", "forest");
        t("alpha_islands_winter", "snowy_plains");
        t("alpine_grove", "grove");
        t("alpine_highlands", "meadow", "windswept_hills");
        t("amethyst_canyon", "jungle");
        t("amethyst_rainforest", "jungle");
        t("ancient_sands", "desert");
        t("arid_highlands", "savanna_plateau");
        t("ashen_savanna", "savanna");
        t("basalt_cliffs", "stony_shore");
        t("birch_taiga", "birch_forest", "taiga");
        t("blooming_plateau", "meadow");
        t("blooming_valley", "meadow", "flower_forest");
        t("brushland", "savanna");
        t("bryce_canyon", "badlands", "eroded_badlands");
        t("caldera", "windswept_hills");
        t("cloud_forest", "windswept_forest");
        t("cold_shrubland", "taiga", "windswept_hills");
        t("deep_warm_ocean", "beach");
        t("desert_canyon", "desert", "badlands");
        t("desert_oasis", "desert");
        t("desert_spires", "desert");
        t("emerald_peaks", "stony_peaks");
        t("forested_highlands", "forest", "windswept_hills");
        t("fractured_savanna", "windswept_savanna");
        t("frozen_cliffs", "frozen_peaks");
        t("glacial_chasm", "ice_spikes");
        t("granite_cliffs", "stony_shore");
        t("gravel_beach", "stony_shore");
        t("gravel_desert", "windswept_gravelly_hills");
        t("haze_mountain", "windswept_hills", "meadow");
        t("highlands", "meadow", "windswept_hills");
        t("hot_shrubland", "savanna");
        t("ice_marsh", "swamp", "snowy_plains");
        t("jungle_mountains", "jungle");
        t("lavender_forest", "flower_forest");
        t("lavender_valley", "flower_forest", "meadow");
        t("lush_desert", "desert");
        t("lush_valley", "meadow", "forest");
        t("mirage_isles", "meadow");
        t("moonlight_grove", "forest");
        t("moonlight_valley", "meadow");
        t("orchid_swamp", "swamp");
        t("painted_mountains", "badlands");
        t("red_oasis", "badlands", "desert");
        t("rocky_jungle", "sparse_jungle");
        t("rocky_mountains", "stony_peaks");
        t("rocky_shrubland", "windswept_gravelly_hills");
        t("sakura_grove", "cherry_grove");
        t("sakura_valley", "cherry_grove");
        t("sandstone_valley", "desert");
        t("savanna_badlands", "wooded_badlands", "savanna");
        t("savanna_slopes", "savanna_plateau");
        t("scarlet_mountains", "windswept_forest");
        t("shield", "taiga", "forest");
        t("shield_clearing", "meadow", "taiga");
        t("shrubland", "savanna", "plains");
        t("siberian_grove", "snowy_taiga");
        t("siberian_taiga", "snowy_taiga");
        t("skylands_autumn", "forest");
        t("skylands_spring", "meadow");
        t("skylands_summer", "plains");
        t("skylands_winter", "snowy_plains");
        t("snowy_badlands", "badlands", "snowy_plains");
        t("snowy_cherry_grove", "cherry_grove", "grove");
        t("snowy_maple_forest", "snowy_taiga");
        t("snowy_shield", "snowy_taiga");
        t("steppe", "plains", "windswept_hills");
        t("stony_spires", "stony_peaks");
        t("temperate_highlands", "meadow", "windswept_hills");
        t("tropical_jungle", "jungle");
        t("valley_clearing", "plains", "meadow");
        t("volcanic_crater", "stony_peaks");
        t("volcanic_peaks", "stony_peaks");
        t("warm_river", "river");
        t("warped_mesa", "badlands");
        t("white_cliffs", "stony_shore");
        t("white_mesa", "badlands");
        t("windswept_spires", "windswept_hills");
        t("wintry_forest", "snowy_taiga");
        t("wintry_lowlands", "snowy_plains");
        t("yellowstone", "meadow", "taiga");
        t("yosemite_cliffs", "windswept_forest");
        t("yosemite_lowlands", "forest", "meadow");

        // ---- Regions Unexplored -----------------------------------------------
        r("alpha_grove", "forest", "plains");
        r("arid_mountains", "savanna_plateau", "badlands");
        r("ashen_woodland", "wooded_badlands");
        r("autumnal_maple_forest", "forest");
        r("bamboo_forest", "bamboo_jungle");
        r("baobab_savanna", "savanna");
        r("barley_fields", "plains", "sunflower_plains");
        r("bayou", "swamp");
        r("blackwood_taiga", "dark_forest", "taiga");
        r("boreal_taiga", "taiga");
        r("chalk_cliffs", "windswept_hills", "stony_shore");
        r("clover_plains", "plains");
        r("cold_boreal_taiga", "snowy_taiga");
        r("cold_deciduous_forest", "grove", "snowy_taiga");
        r("cold_river", "river");
        r("deciduous_forest", "forest");
        r("dry_bushland", "savanna");
        r("eucalyptus_forest", "forest", "savanna");
        r("fen", "swamp");
        r("flower_fields", "meadow", "sunflower_plains");
        r("frozen_pine_taiga", "snowy_taiga");
        r("frozen_tundra", "snowy_plains");
        r("fungal_fen", "swamp", "mushroom_fields");
        r("golden_boreal_taiga", "taiga");
        r("grassland", "plains");
        r("grassy_beach", "beach");
        r("gravel_beach", "stony_shore");
        r("highland_fields", "meadow", "windswept_hills");
        r("hyacinth_deeps", "beach");
        r("icy_heights", "frozen_peaks", "snowy_slopes");
        r("joshua_desert", "desert");
        r("magnolia_woodland", "flower_forest");
        r("maple_forest", "forest");
        r("marsh", "swamp");
        r("mauve_hills", "meadow");
        r("mountains", "windswept_hills");
        r("muddy_river", "river");
        r("old_growth_bayou", "swamp");
        r("old_growth_boreal_taiga", "old_growth_pine_taiga", "taiga");
        r("old_growth_forest", "forest", "dark_forest");
        r("old_growth_golden_boreal_taiga", "old_growth_pine_taiga");
        r("orchard", "meadow", "forest");
        r("outback", "savanna", "badlands");
        r("pine_slopes", "grove");
        r("pine_taiga", "taiga");
        r("poppy_fields", "meadow", "plains");
        r("prairie", "plains");
        r("pumpkin_fields", "plains", "forest");
        r("rainforest", "jungle");
        r("redwoods", "forest", "old_growth_pine_taiga");
        r("rocky_meadow", "meadow");
        r("rocky_reef", "beach");
        r("saguaro_desert", "desert");
        r("shrubland", "plains", "savanna");
        r("silver_birch_forest", "birch_forest");
        r("sparse_rainforest", "sparse_jungle");
        r("sparse_redwoods", "forest", "taiga");
        r("spires", "ice_spikes");
        r("steppe", "savanna", "plains");
        r("temperate_grove", "forest", "meadow");
        r("towering_cliffs", "windswept_hills", "stony_peaks");
        r("tropical_river", "river");
        r("tropics", "jungle", "beach");
        r("tundra", "snowy_plains");
        r("willow_forest", "swamp", "forest");
        r("windswept_maple_forest", "windswept_forest");
        r("wisteria_grove", "flower_forest", "cherry_grove");

        // ---- One each ---------------------------------------------------------
        // Integrated Dynamics' menril woods, and EvilCraft's corrupted land -
        // both overworld biomes, the second spread over existing terrain.
        put("integrateddynamics:meneglin", "forest", "meadow");
        put("evilcraft:degraded", "dark_forest");
    }

    private BiomeAnalogues() {
    }

    private static void t(String id, String... vanilla) {
        put("terralith:" + id, vanilla);
    }

    private static void r(String id, String... vanilla) {
        put("regions_unexplored:" + id, vanilla);
    }

    private static void put(String id, String... vanilla) {
        String[] ids = new String[vanilla.length];
        for (int i = 0; i < vanilla.length; i++) {
            ids[i] = "minecraft:" + vanilla[i];
        }
        if (ANALOGUES.put(id, Collections.unmodifiableList(Arrays.asList(ids))) != null) {
            throw new IllegalStateException("biome analogue listed twice: " + id);
        }
    }

    /** The vanilla biomes {@code biomeId} stands in for; empty for a vanilla or unknown biome. */
    public static List<String> of(String biomeId) {
        List<String> out = ANALOGUES.get(biomeId);
        return out == null ? Collections.emptyList() : out;
    }

    /**
     * Does a list of biome ids - a breed's, or the feral setting's - cover
     * {@code biomeId}, either by naming it or by naming what it stands in for?
     */
    public static boolean covers(Collection<String> listed, String biomeId) {
        if (listed.contains(biomeId)) {
            return true;
        }
        for (String analogue : of(biomeId)) {
            if (listed.contains(analogue)) {
                return true;
            }
        }
        return false;
    }

    /** Every modded biome the table knows, sorted - for tests and the wiki. */
    public static Set<String> moddedBiomes() {
        return Collections.unmodifiableSet(new TreeSet<>(ANALOGUES.keySet()));
    }
}
