// GENERATED by :common:bakeCreatorAssets from
// common/src/main/resources/horsegenetics/example-genes/*.json - the same
// files :common:test parses and :common:bakeSpecFixtures bakes. Inlined
// rather than fetched so the creator works from file://.
window.HG = window.HG || {};
window.HG.examples = {
  "Silver dapple (dilution, no randomness)": {
    "format": 3,
    "key": "example.silver",
    "name": "Silver dapple",
    "phase": "natural",
    "priority": 45,
    "alleles": [
      { "token": "Z", "label": "Silver (Z)" },
      { "token": "z", "label": "Wild-type (z)" }
    ],
    "expressions": [
      {
        "id": "silver",
        "name": "Silver dapple",
        "description": "Black pigment diluted to chocolate, and the mane and tail taken most of the way to flaxen, with red left alone - so a chestnut carrying it looks unchanged.",
        "when": [ "Z/Z", "Z/z" ],
        "layers": [
          {
            "name": "dilute the black, leave the red",
            "masks": [ { "type": "ALL" } ],
            "op": { "type": "DILUTE", "keepRed": 1.0, "keepBlack": 0.45, "blackTint": 0.18 }
          },
          {
            "name": "flaxen mane and tail",
            "masks": [ { "type": "PARTS", "parts": [ "HAIR" ] } ],
            "op": { "type": "DILUTE", "keepRed": 0.9, "keepBlack": 0.12, "blackTint": 0.3 }
          }
        ]
      },
      {
        "id": "wild",
        "name": "Wild type",
        "description": "Black pigment is left alone.",
        "wildType": true
      }
    ],
    "founders": {
      "Z/Z": 0.027778,
      "Z/z": 3.277778,
      "z/z": 96.694444
    }
  },
  "Dun (dilution + dorsal stripe + leg bars)": {
    "format": 3,
    "key": "example.dun",
    "name": "Dun",
    "phase": "natural",
    "priority": 30,
    "alleles": [
      { "token": "D", "label": "Dun (D)" },
      { "token": "d", "label": "Wild-type (d)" }
    ],
    "knobs": [
      { "name": "barSeed", "type": "seed" },
      { "name": "barHeight", "min": 0.25, "max": 0.6, "per": "leg", "spread": 0.18 },
      { "name": "dorsalWidth", "min": 0.7, "max": 1.6 }
    ],
    "expressions": [
      {
        "id": "dun",
        "name": "Dun",
        "description": "The body lightens while a dorsal stripe down the spine and faint bars across the legs keep their colour. One copy is as dun as two.",
        "when": [ "D/D", "D/d" ],
        "layers": [
          {
            "name": "dilute the body, keep the points",
            "masks": [ { "type": "ALL" } ],
            "op": { "type": "DILUTE", "keepRed": 0.62, "keepBlack": 0.7, "blackTint": 0.12 }
          },
          {
            "name": "dorsal stripe down the spine",
            "masks": [
              { "type": "CENTERLINE", "parts": [ "BARREL" ], "halfWidth": "$dorsalWidth", "softness": 0.6 },
              { "type": "AXIS", "axis": "Y", "space": "part", "from": 0.72, "to": 1.0, "softness": 0.18 }
            ],
            "op": { "type": "SET_PIGMENT", "red": 0.05, "black": 0.95 }
          },
          {
            "name": "leg barring",
            "masks": [
              { "type": "STRIPES", "parts": [ "LEGS" ], "seed": "$barSeed",
                "spacing": 1.4, "duty": 0.4, "warp": 0.3 },
              { "type": "AXIS", "parts": [ "LEGS" ], "axis": "Y", "space": "part",
                "from": 0.0, "to": "$barHeight", "softness": 0.2 }
            ],
            "op": { "type": "SET_PIGMENT", "red": 0.1, "black": 0.85 }
          }
        ]
      },
      {
        "id": "wild",
        "name": "Wild type",
        "description": "No dilution and no primitive markings.",
        "wildType": true
      }
    ],
    "founders": {
      "D/D": 0.16,
      "D/d": 7.68,
      "d/d": 92.16
    }
  },
  "Tobiano (white patches, dose-sensitive)": {
    "format": 3,
    "key": "example.tobiano",
    "name": "Tobiano",
    "phase": "natural",
    "priority": 80,
    "alleles": [
      { "token": "To", "label": "Tobiano (To)" },
      { "token": "to", "label": "Wild-type (to)" }
    ],
    "knobs": [
      { "name": "patchSeed", "type": "seed" },
      { "name": "patchScale", "min": 4.0, "max": 8.0 },
      { "name": "sock", "min": 0.2, "max": 0.75, "per": "leg", "spread": 0.25 }
    ],
    "expressions": [
      {
        "id": "tobiano",
        "name": "Tobiano",
        "description": "Big smooth-edged white patches and white socks. Two copies give markedly more white than one - here that is done with a perDose threshold inside a single outcome, but splitting it into two expressions would say the same thing more plainly.",
        "when": [ "To/To", "To/to" ],
        "layers": [
          {
            "name": "white patches, bigger on a homozygote",
            "masks": [
              { "type": "PATCHES", "seed": "$patchSeed", "scale": "$patchScale",
                "threshold": { "perDose": [ 1.0, 0.62, 0.44 ] }, "softness": 0.07 }
            ],
            "op": { "type": "WHITEN", "amount": 1.0 }
          },
          {
            "name": "white socks",
            "masks": [
              { "type": "AXIS", "parts": [ "LEGS" ], "axis": "Y", "space": "part",
                "from": 0.0, "to": "$sock", "softness": 0.12 }
            ],
            "op": { "type": "WHITEN", "amount": 1.0 }
          }
        ]
      },
      {
        "id": "wild",
        "name": "Wild type",
        "description": "No white patches.",
        "wildType": true
      }
    ],
    "founders": {
      "To/To": 0.308642,
      "To/to": 10.493827,
      "to/to": 89.197531
    }
  },
  "Aurora (magical, recessive)": {
    "format": 3,
    "key": "example.aurora",
    "name": "Aurora coat",
    "phase": "magical",
    "priority": 200,
    "alleles": [
      { "token": "Aur", "label": "Aurora (Aur)" },
      { "token": "n", "label": "Wild-type (n)" }
    ],
    "knobs": [
      { "name": "bandSeed", "type": "seed" },
      { "name": "bandSpacing", "min": 3.0, "max": 6.5 }
    ],
    "expressions": [
      {
        "id": "aurora",
        "name": "Aurora coat",
        "description": "Shifting teal bands ripple over the whole horse, deepening to violet wherever the coat underneath is darkest. Both copies are needed.",
        "when": { "Aur": 2 },
        "layers": [
          {
            "name": "teal bands over the whole horse",
            "masks": [
              { "type": "STRIPES", "seed": "$bandSeed", "spacing": "$bandSpacing",
                "duty": 0.5, "warp": 2.2 }
            ],
            "op": { "type": "TOWARD", "color": "#2ee6c1", "strength": 75, "opacity": 100 }
          },
          {
            "name": "violet where the coat is darkest",
            "masks": [
              { "type": "PIGMENT", "channel": "darkness", "from": 0.55, "to": 0.95 }
            ],
            "op": { "type": "TINT", "red": 25, "green": -10, "blue": 60, "opacity": 40 }
          }
        ]
      },
      {
        "id": "carrier",
        "name": "Aurora carrier",
        "description": "One copy shows nothing at all. The allele passes on invisibly, and two carriers bred together are how the aurora coat appears.",
        "wildType": true,
        "when": { "Aur": 1 }
      },
      {
        "id": "wild",
        "name": "Wild type",
        "description": "No aurora.",
        "wildType": true
      }
    ],
    "founders": {
      "Aur/Aur": 1.0,
      "Aur/n": 18.0,
      "n/n": 81.0
    }
  },
  "Prismatic (every shape mask and colour op, once each)": {
    "format": 3,
    "key": "example.prismatic",
    "name": "Prismatic",
    "phase": "magical",
    "priority": 240,
    "blurb": "A demonstration gene, not a real one: it uses every shape mask and every colour op once, so the parity check has something to compare on all of them.",
    "alleles": [
      {
        "token": "Pri",
        "label": "Prismatic (Pri)"
      },
      {
        "token": "n",
        "label": "Wild-type (n)"
      }
    ],
    "knobs": [
      {
        "name": "spotSeed",
        "type": "seed"
      },
      {
        "name": "strokeSeed",
        "type": "seed"
      },
      {
        "name": "coreHue",
        "min": 0.0,
        "max": 360.0
      },
      {
        "name": "spotSize",
        "min": 0.5,
        "max": 1.4
      }
    ],
    "expressions": [
      {
        "id": "prismatic",
        "name": "Prismatic",
        "description": "Glowing spots in the horse's own hue, hollow rings over the barrel, dust along the belly, tapering strokes down the neck, a curl on each shoulder, a spectral tail and an opal blaze. Nothing about it is subtle, which is the point: every primitive is visible at once.",
        "when": [
          "Pri/Pri",
          "Pri/n"
        ],
        "layers": [
          {
            "name": "glowing spots in the horse's own hue",
            "emissive": true,
            "masks": [
              {
                "type": "SPOTS",
                "parts": [
                  "BODY",
                  "NECK"
                ],
                "seed": "$spotSeed",
                "spacing": 3.6,
                "radius": "$spotSize",
                "vary": 0.6,
                "chance": 0.55,
                "stretch": 1.7,
                "axis": "X",
                "softness": 0.2
              }
            ],
            "op": {
              "type": "TOWARD",
              "hue": "$coreHue",
              "saturation": 0.85,
              "lightness": 0.62,
              "strength": 92
            }
          },
          {
            "name": "hollow rings over the barrel",
            "masks": [
              {
                "type": "RINGS",
                "parts": [
                  "BODY"
                ],
                "spacing": 7.0,
                "radius": 2.4,
                "thickness": 0.7,
                "vary": 0.35,
                "chance": 0.7,
                "arc": 0.8,
                "softness": 0.25
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#f5f0ff",
              "strength": 70
            }
          },
          {
            "name": "dust along the belly",
            "masks": [
              {
                "type": "SPECKLE",
                "parts": [
                  "BODY"
                ],
                "spacing": 0.6,
                "size": 0.4,
                "density": 0.45,
                "clumping": 0.7,
                "clumpScale": 6.0
              },
              {
                "type": "AXIS",
                "parts": [
                  "BODY"
                ],
                "axis": "Y",
                "space": "part",
                "from": 0.0,
                "to": 0.35,
                "softness": 0.2
              }
            ],
            "op": {
              "type": "PALETTE",
              "hue": "$coreHue",
              "hueSpread": 55.0,
              "saturation": 0.7,
              "lightness": 0.6,
              "scale": 4.0,
              "strength": 80
            }
          },
          {
            "name": "tapering strokes down the neck",
            "masks": [
              {
                "type": "STROKES",
                "parts": [
                  "NECK"
                ],
                "seed": "$strokeSeed",
                "spacing": 2.0,
                "length": 9.0,
                "axis": "Y",
                "width": 0.6,
                "curl": 0.5,
                "softness": 0.3
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#101018",
              "strength": 85
            }
          },
          {
            "name": "a curl on each shoulder",
            "masks": [
              {
                "type": "SPIRAL",
                "parts": [
                  "BODY"
                ],
                "radius": 5.0,
                "turns": 2.25,
                "width": 0.55,
                "axis": "Z",
                "offset": 0.22,
                "softness": 0.18
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#ffffff",
              "strength": 95
            }
          },
          {
            "name": "a spectral tail, root to tip",
            "masks": [
              {
                "type": "PARTS",
                "parts": [
                  "TAIL",
                  "MANE"
                ]
              }
            ],
            "op": {
              "type": "RAMP",
              "hue": "$coreHue",
              "hueSpan": 210.0,
              "saturation": 0.9,
              "lightness": 0.55,
              "axis": "Y",
              "space": "part",
              "from": 0.9,
              "to": 0.1,
              "strength": 88
            }
          },
          {
            "name": "an opal blaze",
            "masks": [
              {
                "type": "CENTERLINE",
                "parts": [
                  "FACE"
                ],
                "halfWidth": 1.4,
                "softness": 0.5
              }
            ],
            "op": {
              "type": "PALETTE",
              "colors": [
                "#bfe9ff",
                "#c8ffe0",
                "#e3d1ff",
                "#ffe6c9"
              ],
              "scale": 2.5,
              "strength": 90
            }
          },
          {
            "name": "waves of light along the barrel",
            "masks": [
              {
                "type": "WAVES",
                "parts": [
                  "BODY"
                ],
                "seed": "$strokeSeed",
                "axis": "X",
                "across": "Y",
                "space": "units",
                "from": -0.4,
                "to": 0.4,
                "wavelength": 11.0,
                "amplitude": 1.4,
                "spacing": 3.2,
                "phase": 0.6,
                "softness": 0.3
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#9fd6ff",
              "strength": 74
            }
          },
          {
            "name": "a giraffe panel over the hindquarter",
            "masks": [
              {
                "type": "CRACKLE",
                "parts": [
                  "BODY"
                ],
                "seed": "$spotSeed",
                "scale": 4.2,
                "gap": 0.6,
                "warp": 0.4,
                "chance": 0.8,
                "softness": 0.06
              },
              {
                "type": "AXIS",
                "parts": [
                  "BODY"
                ],
                "axis": "X",
                "space": "part",
                "from": 0.0,
                "to": 0.32,
                "softness": 0.1
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#3a2a12",
              "strength": 80
            }
          },
          {
            "name": "hearts on the shoulder, matched left to right",
            "masks": [
              {
                "type": "SPOTS",
                "parts": [
                  "NECK"
                ],
                "seed": "$spotSeed",
                "spacing": 3.4,
                "radius": 1.1,
                "vary": 0.3,
                "chance": 0.6,
                "stretch": 1.0,
                "axis": "X",
                "shape": "heart",
                "softness": 0.12,
                "mirror": true
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#ff5fa2",
              "strength": 88
            }
          },
          {
            "name": "a halo grown out of whatever white the horse has",
            "masks": [
              {
                "type": "PIGMENT",
                "parts": [
                  "BODY",
                  "NECK",
                  "HEAD",
                  "LEGS"
                ],
                "channel": "total",
                "from": 0.05,
                "to": 0.3,
                "spread": 2.5,
                "invert": true
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#cfe9ff",
              "strength": 55
            }
          },
          {
            "name": "the black the gradient chart actually produced, edged in violet",
            "masks": [
              {
                "type": "LUMA",
                "parts": [
                  "BODY",
                  "NECK",
                  "HEAD",
                  "LEGS"
                ],
                "channel": "dark",
                "from": 0.62,
                "to": 0.9,
                "spread": 1.25
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#6c3cc4",
              "strength": 48
            }
          },
          {
            "name": "and the white the chart actually produced, warmed",
            "masks": [
              {
                "type": "LUMA",
                "parts": [
                  "BODY",
                  "NECK",
                  "HEAD",
                  "LEGS"
                ],
                "channel": "white",
                "from": 0.72,
                "to": 0.96
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#ffd9a8",
              "strength": 34
            }
          },
          {
            "name": "a wireframe rim round every box",
            "masks": [
              {
                "type": "EDGE",
                "parts": [
                  "BODY",
                  "NECK",
                  "HEAD",
                  "LEGS"
                ],
                "width": 0.7,
                "softness": 0.3
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#33e0ff",
              "strength": 60
            }
          },
          {
            "name": "and a stain along the underside of that white, grown downward",
            "masks": [
              {
                "type": "LUMA",
                "parts": [
                  "BODY",
                  "NECK",
                  "LEGS"
                ],
                "channel": "white",
                "from": 0.8,
                "to": 0.94
              },
              {
                "type": "LUMA",
                "parts": [
                  "BODY",
                  "NECK",
                  "LEGS"
                ],
                "channel": "white",
                "from": 0.8,
                "to": 0.94,
                "spread": 1.4,
                "spreadFrom": "below",
                "invert": true,
                "combine": "MULTIPLY"
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#8e1122",
              "strength": 70
            }
          },
          {
            "name": "a sawtooth and a zigzag edge on the shoulder",
            "masks": [
              {
                "type": "WAVES",
                "parts": [
                  "NECK"
                ],
                "seed": "$strokeSeed",
                "axis": "Y",
                "across": "X",
                "shape": "triangle",
                "space": "part",
                "from": 0.0,
                "to": 0.45,
                "wavelength": 3.0,
                "amplitude": 0.12,
                "softness": 0.01
              },
              {
                "type": "WAVES",
                "parts": [
                  "NECK"
                ],
                "seed": "$spotSeed",
                "axis": "X",
                "across": "Y",
                "shape": "saw",
                "space": "part",
                "from": 0.3,
                "to": 1.0,
                "wavelength": 4.0,
                "amplitude": 0.1,
                "softness": 0.01,
                "combine": "MIN"
              }
            ],
            "op": {
              "type": "TOWARD",
              "color": "#ffe08a",
              "strength": 70
            }
          },
          {
            "name": "and one hind leg negated, so the parity check sees INVERT too",
            "masks": [
              {
                "type": "PARTS",
                "parts": [
                  "LEFT_HIND_LEG"
                ]
              },
              {
                "type": "AXIS",
                "parts": [
                  "LEFT_HIND_LEG"
                ],
                "axis": "Y",
                "space": "part",
                "from": 0.0,
                "to": 0.6,
                "softness": 0.15
              }
            ],
            "op": {
              "type": "INVERT",
              "amount": 85.0
            }
          }
        ]
      },
      {
        "id": "wild",
        "name": "Wild type",
        "description": "Nothing prismatic.",
        "wildType": true
      }
    ],
    "founders": {
      "Pri/Pri": 0.25,
      "Pri/n": 9.75,
      "n/n": 90.0
    }
  }
};

// Example label by source file - the key the parity fixtures use.
window.HG.exampleFiles = {
  "silver.json": "Silver dapple (dilution, no randomness)",
  "dun.json": "Dun (dilution + dorsal stripe + leg bars)",
  "tobiano.json": "Tobiano (white patches, dose-sensitive)",
  "aurora.json": "Aurora (magical, recessive)",
  "prismatic.json": "Prismatic (every shape mask and colour op, once each)"
};
