// GENERATED by :common:bakeCreatorAssets from
// common/src/main/resources/horsegenetics/example-genes/*.json - the same
// files :common:test parses and :common:bakeSpecFixtures bakes. Inlined
// rather than fetched so the creator works from file://.
window.HG = window.HG || {};
window.HG.examples = {
  "Silver dapple (dilution, no randomness)": {
    "format": 1,
    "key": "example.silver",
    "name": "Silver dapple",
    "phase": "natural",
    "dominance": "DOMINANT",
    "wildOdds": 60,
    "priority": 45,
    "alleles": [
      { "token": "Z", "label": "Silver (Z)" },
      { "token": "z", "label": "Wild-type (z)" }
    ],
    "layers": [
      {
        "name": "dilute the black, leave the red",
        "masks": [ { "type": "ALL" } ],
        "op": { "type": "DILUTE", "keepRed": 1.0, "keepBlack": 0.45, "blackTint": 0.18 }
      },
      {
        "name": "flaxen mane and tail",
        "masks": [ { "type": "PARTS", "parts": [ "HAIR" ] } ],
        "op": { "type": "DILUTE", "keepRed": 0.9, "keepBlack": 0.12, "blackTint": 0.3 }
      }
    ]
  },
  "Dun (dilution + dorsal stripe + leg bars)": {
    "format": 1,
    "key": "example.dun",
    "name": "Dun",
    "phase": "natural",
    "dominance": "DOMINANT",
    "wildOdds": 25,
    "priority": 30,
    "alleles": [
      { "token": "D", "label": "Dun (D)" },
      { "token": "d", "label": "Wild-type (d)" }
    ],
    "knobs": [
      { "name": "barSeed", "type": "seed" },
      { "name": "barHeight", "min": 0.25, "max": 0.6, "per": "leg", "spread": 0.18 },
      { "name": "dorsalWidth", "min": 0.7, "max": 1.6 }
    ],
    "layers": [
      {
        "name": "dilute the body, keep the points",
        "masks": [ { "type": "ALL" } ],
        "op": { "type": "DILUTE", "keepRed": 0.62, "keepBlack": 0.7, "blackTint": 0.12 }
      },
      {
        "name": "dorsal stripe down the spine",
        "masks": [
          { "type": "CENTERLINE", "parts": [ "BARREL" ], "halfWidth": "$dorsalWidth", "softness": 0.6 },
          { "type": "AXIS", "axis": "Y", "space": "part", "from": 0.72, "to": 1.0, "softness": 0.18 }
        ],
        "op": { "type": "SET_PIGMENT", "red": 0.05, "black": 0.95 }
      },
      {
        "name": "leg barring",
        "masks": [
          { "type": "STRIPES", "parts": [ "LEGS" ], "seed": "$barSeed",
            "spacing": 1.4, "duty": 0.4, "warp": 0.3 },
          { "type": "AXIS", "parts": [ "LEGS" ], "axis": "Y", "space": "part",
            "from": 0.0, "to": "$barHeight", "softness": 0.2 }
        ],
        "op": { "type": "SET_PIGMENT", "red": 0.1, "black": 0.85 }
      }
    ]
  },
  "Tobiano (white patches, dose-sensitive)": {
    "format": 1,
    "key": "example.tobiano",
    "name": "Tobiano",
    "phase": "natural",
    "dominance": "INCOMPLETE_DOMINANT",
    "wildOdds": 18,
    "priority": 80,
    "alleles": [
      { "token": "To", "label": "Tobiano (To)" },
      { "token": "to", "label": "Wild-type (to)" }
    ],
    "knobs": [
      { "name": "patchSeed", "type": "seed" },
      { "name": "patchScale", "min": 4.0, "max": 8.0 },
      { "name": "sock", "min": 0.2, "max": 0.75, "per": "leg", "spread": 0.25 }
    ],
    "layers": [
      {
        "name": "white patches, bigger on a homozygote",
        "masks": [
          { "type": "PATCHES", "seed": "$patchSeed", "scale": "$patchScale",
            "threshold": { "perDose": [ 1.0, 0.62, 0.44 ] }, "softness": 0.07 }
        ],
        "op": { "type": "SET_PIGMENT", "red": 0.0, "black": 0.0 }
      },
      {
        "name": "white socks",
        "masks": [
          { "type": "AXIS", "parts": [ "LEGS" ], "axis": "Y", "space": "part",
            "from": 0.0, "to": "$sock", "softness": 0.12 }
        ],
        "op": { "type": "SET_PIGMENT", "red": 0.0, "black": 0.0 }
      }
    ]
  },
  "Aurora (magical, recessive)": {
    "format": 1,
    "key": "example.aurora",
    "name": "Aurora coat",
    "phase": "magical",
    "dominance": "RECESSIVE",
    "wildOdds": 10,
    "priority": 200,
    "alleles": [
      { "token": "Aur", "label": "Aurora (Aur)" },
      { "token": "n", "label": "Wild-type (n)" }
    ],
    "knobs": [
      { "name": "bandSeed", "type": "seed" },
      { "name": "bandSpacing", "min": 3.0, "max": 6.5 }
    ],
    "layers": [
      {
        "name": "teal bands over the whole horse",
        "masks": [
          { "type": "STRIPES", "seed": "$bandSeed", "spacing": "$bandSpacing",
            "duty": 0.5, "warp": 2.2 }
        ],
        "op": { "type": "TOWARD", "color": "#2ee6c1", "strength": 75, "opacity": 100 }
      },
      {
        "name": "violet where the coat is darkest",
        "masks": [
          { "type": "PIGMENT", "channel": "darkness", "from": 0.55, "to": 0.95 }
        ],
        "op": { "type": "TINT", "red": 25, "green": -10, "blue": 60, "opacity": 40 }
      }
    ]
  }
};
