// Inlines assets/grass.jpg into assets/grass.js as a data URI.
//
// Same reason the gene creator inlines its coat templates: the wiki has to work
// from a file:// path, and a file:// page cannot read an image file sitting
// beside it - the browser treats every local file as its own opaque origin, so
// the fetch is blocked and the canvas would be tainted even if it were not.
//
//   node wiki/horse-designer/tools/bake-grass.mjs
//
// Re-run it if grass.jpg is replaced. The .jpg stays checked in as the source
// of truth; grass.js is generated and should never be hand-edited.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const assets = join(here, "..", "assets");

const jpg = readFileSync(join(assets, "grass.jpg"));
const uri = "data:image/jpeg;base64," + jpg.toString("base64");

const out = `// GENERATED by tools/bake-grass.mjs from assets/grass.jpg - do not hand-edit.
// Inlined because a file:// page cannot read an image beside it.
window.HG = window.HG || {};
window.HG.designerAssets = window.HG.designerAssets || {};
window.HG.designerAssets.GRASS_JPG = "${uri}";
`;

writeFileSync(join(assets, "grass.js"), out);
console.log(`grass.js written: ${jpg.length} bytes of JPEG -> ${uri.length} chars of data URI`);
