package com.example.horsegenetics.common.genetics.spec;

import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;

/**
 * Regenerates the gene creator's two generated files from the mod's own assets:
 * {@code assets/textures.js} (the coat templates and the red/black gradient) and
 * {@code js/examples.js} (the worked example genes).
 *
 * <p><b>Why they are generated rather than fetched.</b> The creator has to work
 * when the wiki is opened straight off disk. Under {@code file://} a browser
 * will not let a page read the pixels back out of an image loaded from a sibling
 * file (tainted canvas) and will not load an ES module at all - so the textures
 * are inlined as data URIs and every script is a classic one.
 *
 * <p>The gradient is downsampled to {@value #GRADIENT_SIZE}px. The composer
 * samples it bilinearly, so the preview is visually the same coat; it is
 * deliberately not byte-exact with an in-game bake, and the creator says so.
 *
 * <p>{@code ./gradlew :common:bakeCreatorAssets}
 */
public final class CreatorAssetTool {

    public static final int GRADIENT_SIZE = 256;

    private static final String ADULT = "/assets/horsegenetics/textures/entity/horse/horse_white.png";
    private static final String BABY = "/assets/horsegenetics/textures/entity/horse/horse_white_baby.png";
    private static final String GRADIENT = "/assets/horsegenetics/textures/coat/redblackgradient.png";

    /** Example gene files, and the label the creator's menu shows for each. */
    private static final String[][] EXAMPLES = {
            {"silver.json", "Silver dapple (dilution, no randomness)"},
            {"dun.json", "Dun (dilution + dorsal stripe + leg bars)"},
            {"tobiano.json", "Tobiano (white patches, dose-sensitive)"},
            {"aurora.json", "Aurora (magical, recessive)"}
    };

    private CreatorAssetTool() {}

    public static void main(String[] args) throws IOException {
        Path creator = Path.of(args.length > 0 ? args[0] : "wiki/gene-creator");
        writeTextures(creator.resolve("assets/textures.js"));
        writeExamples(creator.resolve("js/examples.js"));
    }

    private static void writeTextures(Path out) throws IOException {
        Files.createDirectories(out.getParent());
        StringBuilder sb = new StringBuilder();
        sb.append("""
                // GENERATED from the mod's own assets by :common:bakeCreatorAssets -
                // do not hand-edit. See CreatorAssetTool for why these are inlined.
                //
                // The gradient is downsampled from the game's 500x500. The composer samples
                // it bilinearly, so the preview is visually the same coat - but it is
                // deliberately NOT byte-exact with an in-game bake.
                window.HG = window.HG || {};
                window.HG.textures = {
                """);
        sb.append("  ADULT_TEMPLATE_PNG: ").append(dataUri(read(ADULT))).append(",\n");
        sb.append("  BABY_TEMPLATE_PNG: ").append(dataUri(read(BABY))).append(",\n");
        sb.append("  GRADIENT_PNG: ").append(dataUri(scale(read(GRADIENT), GRADIENT_SIZE))).append(",\n");
        sb.append("  GRADIENT_SIZE: ").append(GRADIENT_SIZE).append("\n};\n");
        Files.writeString(out, sb.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + out.toAbsolutePath());
    }

    private static void writeExamples(Path out) throws IOException {
        Files.createDirectories(out.getParent());
        StringBuilder sb = new StringBuilder();
        sb.append("""
                // GENERATED by :common:bakeCreatorAssets from
                // common/src/main/resources/horsegenetics/example-genes/*.json - the same
                // files :common:test parses and :common:bakeSpecFixtures bakes. Inlined
                // rather than fetched so the creator works from file://.
                window.HG = window.HG || {};
                window.HG.examples = {
                """);
        List<String> entries = new ArrayList<>();
        for (String[] example : EXAMPLES) {
            String json = new String(readBytes("/horsegenetics/example-genes/" + example[0]),
                    StandardCharsets.UTF_8).stripTrailing();
            // Parsing on the way past is the point: a broken example can never
            // reach the creator's menu.
            GeneSpecParser.parse(json, example[0]);
            entries.add("  " + quote(example[1]) + ": " + json.replace("\n", "\n  "));
        }
        sb.append(String.join(",\n", entries)).append("\n};\n");
        Files.writeString(out, sb.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + out.toAbsolutePath() + " (" + EXAMPLES.length + " examples)");
    }

    // ------------------------------------------------------------------

    private static BufferedImage read(String resource) throws IOException {
        try (InputStream in = CreatorAssetTool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("missing resource " + resource);
            }
            return ImageIO.read(in);
        }
    }

    private static BufferedImage scale(BufferedImage src, int size) {
        BufferedImage out = new BufferedImage(size, size, BufferedImage.TYPE_INT_RGB);
        var g = out.createGraphics();
        g.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(src.getScaledInstance(size, size, Image.SCALE_SMOOTH), 0, 0, null);
        g.dispose();
        return out;
    }

    /** A data URI, split across lines so the file stays diff-able. */
    private static String dataUri(BufferedImage image) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        ImageIO.write(image, "png", bytes);
        String b64 = Base64.getEncoder().encodeToString(bytes.toByteArray());
        StringBuilder sb = new StringBuilder("\"data:image/png;base64,\"");
        for (int i = 0; i < b64.length(); i += 100) {
            sb.append(" +\n    \"").append(b64, i, Math.min(b64.length(), i + 100)).append("\"");
        }
        return sb.toString();
    }

    private static byte[] readBytes(String resource) throws IOException {
        try (InputStream in = CreatorAssetTool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("missing resource " + resource);
            }
            return in.readAllBytes();
        }
    }

    private static String quote(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
