package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.genetics.Allele;
import com.example.horsegenetics.common.genetics.GeneFamily;
import com.example.horsegenetics.common.genetics.Genes;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Writes the wiki's pages for the <b>data-driven genes</b>: one page each, plus
 * a family index that gathers them by what they are made of.
 *
 * <h2>Why these pages are generated and the others are not</h2>
 * Every other page on the wiki is hand-written, and should be: prose about a
 * system is not derivable from the system. These are the exception because
 * there are <b>eighty-odd</b> of the things and almost everything a reader needs
 * about one - its name, its alleles, what each combination does and looks like,
 * how often a wild horse carries it - is already written down in the gene's own
 * file, in the same words the game shows. Copying that into HTML by hand would
 * produce eighty-odd opportunities for the wiki to say something the mod does
 * not.
 *
 * <h2>A hand-written page always wins</h2>
 * A gene with a page of its own that is <b>not</b> marked {@link #GENERATED} is
 * left completely alone, and the family index links to it like any other. That
 * is how Suntouched and Waterborn keep the pages somebody wrote for them. To
 * take a generated page over by hand, delete the marker comment and the tool
 * will never touch it again.
 *
 * <h2>The family is the priority band</h2>
 * A gene declares no family. It does not need to: the magical priority bands
 * were laid out as families in the first place - spots together, strokes
 * together, the things that read the coat beneath them last - because the paint
 * order and the taxonomy want the same grouping for the same reason.
 * {@link GeneFamily} is that table. It lives in {@code genetics/} rather than
 * here because the two gene editors group their gene list by the same families
 * and offer a "re-roll one family" randomize - three readers, one table.
 *
 * <h2>What is <i>not</i> baked into a page</h2>
 * The rarity tier, the gene-carrot recipe and whether the Unknown Splice can
 * land on the locus are all read off the mod at run time by
 * {@code wiki/gene-carrot/}, exactly as on a hand-written page - a tier written
 * into eighty pages goes stale silently the first time a gene is re-tiered. The
 * founder odds <i>are</i> baked, because there is no widget for them; they are
 * in the regeneration table in {@code CLAUDE.md} for that reason.
 *
 * <p>{@code ./gradlew :common:bakeGeneWikiPages} - output dir is arg 0.
 */
public final class GeneWikiTool {

    /**
     * The marker that says a page belongs to this tool. Its absence is a veto:
     * see the class note on hand-written pages.
     */
    public static final String GENERATED = "<!-- GENERATED by :common:bakeGeneWikiPages -->";

    private GeneWikiTool() {}

    public static void main(String[] args) throws IOException {
        Path wiki = Path.of(args.length > 0 ? args[0] : "wiki");

        Map<GeneFamily, List<SpecGene>> byFamily = new LinkedHashMap<>();
        for (GeneFamily family : GeneFamily.magicalSpecFamilies()) {
            byFamily.put(family, new ArrayList<>());
        }
        for (SpecGene gene : Genes.loaded()) {
            byFamily.get(GeneFamily.ofMagicalPriority(gene.priority())).add(gene);
        }

        int written = 0;
        // Genes whose page somebody wrote by hand. They are skipped twice over:
        // the page is never overwritten, and the generated span of pages.js
        // leaves them out - a hand-written page is registered by hand, and
        // listing it in both places puts it in the sidebar twice. The family
        // index still links to it like any other.
        Set<String> handWritten = new LinkedHashSet<>();
        for (SpecGene gene : Genes.loaded()) {
            Path out = wiki.resolve(pageOf(gene));
            if (Files.exists(out) && !Files.readString(out, StandardCharsets.UTF_8)
                    .contains(GENERATED)) {
                handWritten.add(gene.key());
            }
        }

        StringBuilder sections = new StringBuilder();
        for (Map.Entry<GeneFamily, List<SpecGene>> e : byFamily.entrySet()) {
            GeneFamily family = e.getKey();
            List<SpecGene> genes = new ArrayList<>(e.getValue());
            genes.sort((a, b) -> a.name().compareToIgnoreCase(b.name()));

            for (SpecGene gene : genes) {
                if (handWritten.contains(gene.key())) {
                    continue;
                }
                Files.writeString(wiki.resolve(pageOf(gene)), genePage(gene, family),
                        StandardCharsets.UTF_8);
                written++;
            }

            Path index = wiki.resolve(family.slug() + ".html");
            Files.writeString(index, familyPage(family, genes), StandardCharsets.UTF_8);
            sections.append(section(family, genes, handWritten));
        }

        System.out.println("wrote " + written + " gene pages ("
                + handWritten.size() + " hand-written ones left alone: " + handWritten + ")"
                + " and " + GeneFamily.magicalSpecFamilies().size() + " family indexes");
        rewritePages(wiki.resolve("pages.js"), sections.toString());
    }

    private static String slug(SpecGene gene) {
        return gene.key().substring(gene.key().indexOf('.') + 1);
    }

    /** The page a gene lives on. Hyphens, to match the hand-written pages beside them. */
    private static String pageOf(SpecGene gene) {
        return "gene-" + slug(gene).replace('_', '-') + ".html";
    }

    // ------------------------------------------------------------------
    // pages.js
    // ------------------------------------------------------------------

    private static final String BEGIN = "        /* BEGIN generated by :common:bakeGeneWikiPages";
    private static final String END = "        /* END generated by :common:bakeGeneWikiPages */";

    /**
     * Replace the generated span of {@code pages.js} in place.
     *
     * <p>Hard rule 7 says a page is registered in {@code SECTIONS} and nowhere
     * else, and eighty-odd of them cannot be maintained by hand - so the tool
     * writes that part of the file. Everything outside the two markers is left
     * exactly as it was; a hand-written section can sit either side of them.
     */
    private static void rewritePages(Path pages, String sections) throws IOException {
        // Normalise on the way in. A checkout on Windows can leave this file
        // CRLF, and an anchor written with a bare newline then silently matches
        // nothing - which looks exactly like "the section is missing".
        String s = Files.readString(pages, StandardCharsets.UTF_8).replace("\r\n", "\n");
        String block = BEGIN + " - do not edit between the markers.\n"
                + "           One section per magical gene family, each led by its index page.\n"
                + "           Hand-written entries go OUTSIDE this span and are never touched. */\n"
                + sections
                + END + "\n";
        int i = s.indexOf(BEGIN);
        if (i < 0) {
            // First run: land it immediately after the magical-gene section, which
            // is where a reader looking for a magical gene is already looking.
            String anchor = "        {\n            title: \"Gameplay\",";
            int at = s.indexOf(anchor);
            if (at < 0) {
                throw new IllegalStateException("pages.js: no anchor to insert the generated span at");
            }
            s = s.substring(0, at) + block + s.substring(at);
        } else {
            int j = s.indexOf(END, i);
            if (j < 0) {
                throw new IllegalStateException("pages.js: BEGIN marker with no END");
            }
            s = s.substring(0, i) + block + s.substring(j + END.length() + 1);
        }
        Files.writeString(pages, s, StandardCharsets.UTF_8);
        System.out.println("rewrote the generated span of " + pages.getFileName());
    }

    private static String section(GeneFamily family, List<SpecGene> genes, Set<String> handWritten) {
        StringBuilder sb = new StringBuilder();
        sb.append("        {\n            title: \"Magic: ")
                .append(family.title().substring(0, 1).toLowerCase(Locale.ROOT))
                .append(family.title().substring(1)).append("\",\n            items: [\n");
        List<String> items = new ArrayList<>();
        items.add("                { href: \"" + family.slug() + ".html\", text: \"All "
                + family.title().toLowerCase(Locale.ROOT) + "\", kind: \"magical\", "
                + "views: [\"gameplay\",\"coding\"] }");
        for (SpecGene gene : genes) {
            if (handWritten.contains(gene.key())) {
                continue;   // registered by hand, elsewhere in this file
            }
            items.add("                { href: \"" + pageOf(gene) + "\", text: \""
                    + esc(gene.name()) + "\", kind: \"magical\", views: [\"gameplay\",\"coding\"] }");
        }
        sb.append(String.join(",\n", items)).append("\n            ]\n        },\n");
        return sb.toString();
    }

    // ------------------------------------------------------------------
    // The family index
    // ------------------------------------------------------------------

    private static String familyPage(GeneFamily family, List<SpecGene> genes) {
        StringBuilder sb = new StringBuilder();
        head(sb, family.title());
        sb.append("<p class=\"eyebrow magical\">Magical genes <span class=\"sep\">/</span> ")
                .append(genes.size()).append(" in this family</p>\n\n");
        sb.append("<h1>").append(esc(family.title())).append("</h1>\n\n");
        sb.append("<p class=\"lede\">\n    ").append(esc(family.lede())).append("\n</p>\n\n");
        sb.append("<p class=\"note\">\n    An index. <strong>Each of these has its own page</strong>"
                + " - that is where the\n    inheritance table, the gene carrot and how you actually"
                + " come by one live.\n    The picture beside each name is that gene on a standard"
                + " bay, baked through the\n    real coat pipeline rather than drawn.\n</p>\n\n");

        sb.append("<section class=\"tab-panel\" data-tab=\"gameplay\">\n\n");
        for (SpecGene gene : genes) {
            sb.append("<h2 id=\"").append(slug(gene).replace('_', '-')).append("\"><a href=\"")
                    .append(pageOf(gene)).append("\">").append(esc(gene.name())).append("</a></h2>\n\n");
            sb.append("<div class=\"gene-card\">\n");
            sb.append("<a href=\"").append(pageOf(gene)).append("\">")
                    .append("<img class=\"gene-card-icon\" src=\"assets/gene-icons/").append(slug(gene))
                    .append(".png\" alt=\"").append(esc(gene.name()))
                    .append(" on a bay horse\" width=\"150\" loading=\"lazy\"></a>\n");
            sb.append("<div class=\"gene-card-body\">\n");
            if (!gene.spec().blurb().isBlank()) {
                sb.append("<p>").append(esc(gene.spec().blurb())).append("</p>\n");
            }
            sb.append("<p class=\"gene-card-alleles\">").append(alleleList(gene))
                    .append(" &middot; <a href=\"").append(pageOf(gene))
                    .append("\">full page</a></p>\n");
            sb.append("</div>\n</div>\n\n");
        }
        sb.append("</section>\n\n");

        sb.append("<section class=\"tab-panel\" data-tab=\"coding\">\n\n");
        sb.append("<h2 id=\"files\">The files</h2>\n\n");
        sb.append("<p>\n    Each of these is a JSON file in\n    "
                + "<code>common/src/main/resources/horsegenetics/genes/</code>, listed in the\n    "
                + "<code>index.json</code> beside them and loaded by <code>Genes</code>' class\n    "
                + "initialiser. None is a Java class; see\n    "
                + "<a href=\"gene-format.html\">the gene file format</a> for what the masks and "
                + "ops mean.\n</p>\n\n");
        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n<thead><tr>")
                .append("<th>Gene</th><th>File</th><th>Priority</th>")
                .append("<th>Masks and ops it uses</th></tr></thead>\n<tbody>\n");
        for (SpecGene gene : genes) {
            sb.append("<tr><td><a href=\"").append(pageOf(gene)).append("\">")
                    .append(esc(gene.name())).append("</a></td>")
                    .append("<td><code>").append(slug(gene)).append(".json</code></td>")
                    .append("<td>").append(gene.priority()).append("</td>")
                    .append("<td>").append(esc(String.join(", ", vocabulary(gene)))).append("</td></tr>\n");
        }
        sb.append("</tbody>\n</table>\n</div>\n\n</section>\n\n");
        foot(sb);
        return sb.toString();
    }

    // ------------------------------------------------------------------
    // One gene, one page
    // ------------------------------------------------------------------

    private static String genePage(SpecGene gene, GeneFamily family) {
        String slug = slug(gene);
        StringBuilder sb = new StringBuilder();
        head(sb, gene.name());

        sb.append("<p class=\"eyebrow magical\">Magical gene <span class=\"sep\">/</span> ")
                .append("<a href=\"").append(family.slug()).append(".html\">")
                .append(esc(family.title().toLowerCase(Locale.ROOT))).append("</a></p>\n\n");
        sb.append("<h1>").append(esc(gene.name())).append("</h1>\n\n");
        if (!gene.spec().blurb().isBlank()) {
            sb.append("<p class=\"lede\">\n    ").append(esc(gene.spec().blurb())).append("\n</p>\n\n");
        }

        // ---- gameplay -------------------------------------------------
        sb.append("<section class=\"tab-panel\" data-tab=\"gameplay\">\n\n");
        sb.append("<div class=\"gene-preview\" data-gene=\"").append(gene.key()).append("\"></div>\n\n");

        sb.append("<h2 id=\"outcomes\">What it does</h2>\n\n");
        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n<tbody>\n");
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            if (e.description().isBlank()) {
                continue;
            }
            sb.append("<tr><th>").append(esc(e.name())).append("</th><td>")
                    .append(esc(e.description())).append("</td></tr>\n");
        }
        sb.append("</tbody>\n</table>\n</div>\n\n");

        sb.append("<h2 id=\"inheritance\">What you can get</h2>\n\n");
        sb.append("<div class=\"gene-inheritance\" data-gene=\"").append(gene.key())
                .append("\"></div>\n\n");

        sb.append(acquisition(gene));

        sb.append("<h2 id=\"carrot\">Its gene carrot</h2>\n\n");
        sb.append("<!-- The recipe, read off the mod at run time - the rarity tier is the\n"
                + "     recipe's price, and a price written into eighty pages goes stale\n"
                + "     silently. See wiki/gene-carrot/gene-carrot.js. -->\n\n");
        sb.append("<div class=\"gene-carrot\" data-gene=\"").append(gene.key()).append("\"></div>\n\n");
        sb.append("</section>\n\n");

        // ---- coding ---------------------------------------------------
        sb.append("<section class=\"tab-panel\" data-tab=\"coding\">\n\n");
        sb.append("<h2 id=\"file\">The file</h2>\n\n");
        sb.append("<p>\n    <code>common/src/main/resources/horsegenetics/genes/").append(slug)
                .append(".json</code> &mdash; a\n    <a href=\"gene-format.html\">data-driven gene</a>,"
                        + " not a Java class. It is listed in the\n    <code>index.json</code> beside"
                        + " it and registered by <code>Genes</code>' class\n    initialiser at"
                        + " startup.\n</p>\n\n");

        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n<tbody>\n");
        sb.append("<tr><th>Key</th><td><code>").append(gene.key()).append("</code></td></tr>\n");
        sb.append("<tr><th>Phase</th><td>magical &mdash; it adds signed colour in phase 3, "
                + "after the pigment has resolved</td></tr>\n");
        sb.append("<tr><th>Priority</th><td>").append(gene.priority())
                .append(" &mdash; where it sits in the one <code>(priority, key)</code> paint "
                        + "order</td></tr>\n");
        sb.append("<tr><th>Alleles</th><td>").append(alleleList(gene)).append("</td></tr>\n");
        sb.append("<tr><th>Varies per horse</th><td>")
                .append(gene.spec().knobs().isEmpty()
                        ? "no &mdash; every horse carrying it looks the same"
                        : gene.spec().knobs().size() + " value"
                                + (gene.spec().knobs().size() == 1 ? "" : "s")
                                + " drawn once off the expressing allele copy, so a foal that "
                                + "inherits the copy inherits the look")
                .append("</td></tr>\n");
        sb.append("<tr><th>Built from</th><td>")
                .append(esc(String.join(", ", vocabulary(gene)))).append("</td></tr>\n");
        sb.append("</tbody>\n</table>\n</div>\n\n");

        sb.append(layers(gene));
        sb.append("</section>\n\n");
        foot(sb);
        return sb.toString();
    }

    /**
     * How a player actually comes by the gene.
     *
     * <p>The founder table is the one acquisition fact with no run-time widget
     * behind it, so it is baked - hence the gene files' row in
     * {@code CLAUDE.md}'s regeneration table. The rarity tier and the carrot are
     * deliberately <i>not</i> here; the card below reads those off the mod.
     */
    private static String acquisition(SpecGene gene) {
        StringBuilder sb = new StringBuilder();
        sb.append("<h2 id=\"finding\">Finding one</h2>\n\n");

        double showing = 0;
        List<String> rows = new ArrayList<>();
        for (GeneSpec.FounderWeight w : gene.spec().founders()) {
            if (w.percent() <= 0) {
                continue;
            }
            GeneSpec.ExpressionSpec e = expressionFor(gene, w.combination());
            boolean shows = e != null && !e.wildType();
            if (shows) {
                showing += w.percent();
            }
            rows.add("<tr><td><code>" + esc(w.combination()) + "</code></td><td>"
                    + (e == null ? "&mdash;" : esc(e.name())) + "</td><td>"
                    + odds(w.percent()) + "</td></tr>");
        }

        if (showing <= 0) {
            sb.append("<p>\n    <strong>No wild horse carries it.</strong> Every copy in the world"
                    + " came from a\n    gene carrot or a splice; there is nothing to go looking"
                    + " for.\n</p>\n\n");
        } else {
            sb.append("<p>\n    About <strong>").append(oneIn(showing))
                    .append("</strong> wild horses is born showing this. That is the whole of the"
                            + "\n    supply: catch one, or make one with the carrot below. Breeds set"
                            + " their own\n    pools and a breed built around this gene will carry it"
                            + " far more often than\n    the wild population does.\n</p>\n\n");
        }

        if (!rows.isEmpty()) {
            sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n")
                    .append("<thead><tr><th>Wild pair</th><th>Shows as</th><th>How often</th>")
                    .append("</tr></thead>\n<tbody>\n")
                    .append(String.join("\n", rows))
                    .append("\n</tbody>\n</table>\n</div>\n\n");
        }
        return sb.toString();
    }

    private static GeneSpec.ExpressionSpec expressionFor(SpecGene gene, String combination) {
        GeneSpec.ExpressionSpec catchAll = null;
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            if (e.isCatchAll()) {
                catchAll = e;
            } else if (e.combinations().contains(combination)) {
                return e;
            }
        }
        return catchAll;
    }

    /**
     * A percentage as something a player can picture. Past a half the "1 in N"
     * form stops helping - "99.92% - 1 in 1" is worse than the percentage on its
     * own - so the common case just says the number.
     */
    private static String odds(double percent) {
        if (percent > 50) {
            return trim(percent) + "%";
        }
        return String.format(Locale.ROOT, "%s%% &mdash; %s", trim(percent), oneIn(percent));
    }

    private static String oneIn(double percent) {
        if (percent >= 100) {
            return "every horse";
        }
        long n = Math.round(100.0 / percent);
        return "1 in " + String.format(Locale.ROOT, "%,d", n);
    }

    private static String trim(double v) {
        String s = String.format(Locale.ROOT, "%.4f", v);
        while (s.contains(".") && (s.endsWith("0") || s.endsWith("."))) {
            s = s.substring(0, s.length() - 1);
        }
        return s;
    }

    private static String layers(SpecGene gene) {
        StringBuilder sb = new StringBuilder("<h2 id=\"layers\">What it paints</h2>\n\n");
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            if (e.layers().isEmpty()) {
                continue;
            }
            sb.append("<h3>").append(esc(e.name())).append("</h3>\n\n");
            sb.append("<ol>\n");
            for (GeneSpec.Layer layer : e.layers()) {
                sb.append("<li>").append(esc(layer.name()));
                List<String> masks = new ArrayList<>();
                for (GeneSpec.Mask mask : layer.masks()) {
                    masks.add("<code>" + mask.type() + (mask.invert() ? " inverted" : "") + "</code>");
                }
                sb.append(" &mdash; ").append(String.join(" &times; ", masks))
                        .append(", painted with <code>").append(layer.op().type()).append("</code>");
                if (layer.emissive()) {
                    sb.append(", and it <strong>glows</strong>");
                }
                sb.append("</li>\n");
            }
            sb.append("</ol>\n\n");
        }
        return sb.toString();
    }

    // ------------------------------------------------------------------

    private static String alleleList(SpecGene gene) {
        List<String> tokens = new ArrayList<>();
        for (Allele a : gene.alleles()) {
            tokens.add("<code>" + esc(a.token()) + "</code>");
        }
        return String.join(" &middot; ", tokens);
    }

    private static List<String> vocabulary(SpecGene gene) {
        Set<String> out = new LinkedHashSet<>();
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            for (GeneSpec.Layer layer : e.layers()) {
                for (GeneSpec.Mask mask : layer.masks()) {
                    out.add(mask.type().name());
                }
                out.add(layer.op().type().name());
                if (layer.emissive()) {
                    out.add("emissive");
                }
            }
        }
        List<String> sorted = new ArrayList<>(out);
        sorted.sort(String::compareTo);
        return sorted;
    }

    private static void head(StringBuilder sb, String title) {
        sb.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n").append(GENERATED).append('\n')
                .append("<meta charset=\"UTF-8\">\n")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
                .append("<title>").append(esc(title)).append(" &middot; Horse Genetics Wiki</title>\n")
                .append("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/")
                .append("prism/1.29.0/themes/prism-tomorrow.min.css\">\n")
                .append("<link rel=\"stylesheet\" href=\"styles.css\">\n")
                .append("<script defer src=\"pages.js\"></script>\n")
                .append("<script defer src=\"tabs.js\"></script>\n")
                .append("<script defer src=\"nav.js\"></script>\n")
                .append("<script defer src=\"search.js\"></script>\n")
                .append("</head>\n<body>\n<main class=\"content\">\n<article class=\"doc\">\n\n");
    }

    private static void foot(StringBuilder sb) {
        sb.append("</article>\n</main>\n")
                .append("<script defer src=\"gene-preview/gene-preview.js\"></script>\n")
                .append("<script defer src=\"gene-inheritance/gene-inheritance.js\"></script>\n")
                .append("<script defer src=\"gene-carrot/gene-carrot.js\"></script>\n")
                .append("</body>\n</html>\n");
    }

    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
