package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.genetics.Allele;
import com.example.horsegenetics.common.genetics.Gene;
import com.example.horsegenetics.common.genetics.GeneFamily;
import com.example.horsegenetics.common.genetics.Genes;
import com.example.horsegenetics.common.genetics.GenotypeCatalog;
import com.example.horsegenetics.common.breed.Breeds;

import java.io.IOException;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes the wiki's pages for the <b>data-driven genes</b>: one page each, plus
 * a family index that gathers them by what they are made of.
 *
 * <h2>Why these pages are generated and the others are not</h2>
 * Every other page on the wiki is hand-written, and should be: prose about a
 * system is not derivable from the system. These are the exception because
 * there are <b>eighty-odd</b> of the things and almost everything a reader needs
 * about one - its name, its alleles, what each combination does and looks like,
 * how often a wild horse carries it - is already written down in the gene's own
 * file, in the same words the game shows. Copying that into HTML by hand would
 * produce eighty-odd opportunities for the wiki to say something the mod does
 * not.
 *
 * <h2>A hand-written page always wins</h2>
 * A gene with a page of its own that is <b>not</b> marked {@link #GENERATED} is
 * left completely alone, and the family index links to it like any other. That
 * is how Suntouched and Waterborn keep the pages somebody wrote for them. To
 * take a generated page over by hand, delete the marker comment and the tool
 * will never touch it again.
 *
 * <h2>The family is the priority band</h2>
 * A gene declares no family. It does not need to: the magical priority bands
 * were laid out as families in the first place - spots together, strokes
 * together, the things that read the coat beneath them last - because the paint
 * order and the taxonomy want the same grouping for the same reason.
 * {@link GeneFamily} is that table. It lives in {@code genetics/} rather than
 * here because the two gene editors group their gene list by the same families
 * and offer a "re-roll one family" randomize - three readers, one table.
 *
 * <h2>What is <i>not</i> baked into a page</h2>
 * The rarity tier, the gene-carrot recipe and whether the Unknown Splice can
 * land on the locus are all read off the mod at run time by
 * {@code wiki/gene-carrot/}, exactly as on a hand-written page - a tier written
 * into eighty pages goes stale silently the first time a gene is re-tiered. The
 * founder odds <i>are</i> baked, because there is no widget for them; they are
 * in the regeneration table in {@code CLAUDE.md} for that reason.
 *
 * <p>{@code ./gradlew :common:bakeGeneWikiPages} - output dir is arg 0.
 */
public final class GeneWikiTool {

    /**
     * The marker that says a page belongs to this tool. Its absence is a veto:
     * see the class note on hand-written pages.
     */
    public static final String GENERATED = "<!-- GENERATED by :common:bakeGeneWikiPages -->";

    private GeneWikiTool() {}

    public static void main(String[] args) throws IOException {
        Path wiki = Path.of(args.length > 0 ? args[0] : "wiki");

        Map<GeneFamily, List<SpecGene>> byFamily = new LinkedHashMap<>();
        for (GeneFamily family : GeneFamily.magicalSpecFamilies()) {
            byFamily.put(family, new ArrayList<>());
        }
        for (SpecGene gene : Genes.loaded()) {
            byFamily.get(GeneFamily.ofMagicalPriority(gene.priority())).add(gene);
        }

        int written = 0;
        // Genes whose page somebody wrote by hand. They are skipped twice over:
        // the page is never overwritten, and the generated span of pages.js
        // leaves them out - a hand-written page is registered by hand, and
        // listing it in both places puts it in the sidebar twice. The family
        // index still links to it like any other.
        Set<String> handWritten = new LinkedHashSet<>();
        for (SpecGene gene : Genes.loaded()) {
            Path out = wiki.resolve(pageOf(gene));
            if (Files.exists(out) && !Files.readString(out, StandardCharsets.UTF_8)
                    .contains(GENERATED)) {
                handWritten.add(gene.key());
            }
        }

        for (Map.Entry<GeneFamily, List<SpecGene>> e : byFamily.entrySet()) {
            GeneFamily family = e.getKey();
            List<SpecGene> genes = new ArrayList<>(e.getValue());
            genes.sort((a, b) -> a.name().compareToIgnoreCase(b.name()));

            for (SpecGene gene : genes) {
                if (handWritten.contains(gene.key())) {
                    continue;
                }
                Files.writeString(wiki.resolve(pageOf(gene)), genePage(gene, family),
                        StandardCharsets.UTF_8);
                written++;
            }

            Path index = wiki.resolve(family.slug() + ".html");
            Files.writeString(index, familyPage(family, genes), StandardCharsets.UTF_8);
        }

        System.out.println("wrote " + written + " gene pages ("
                + handWritten.size() + " hand-written ones left alone: " + handWritten + ")"
                + " and " + GeneFamily.magicalSpecFamilies().size() + " family indexes");

        // Both of these list EVERY gene, not only the data-driven ones - see
        // geneSections. A gene page that nobody registered is unreachable from
        // the sidebar and invisible on the landing page, and the only way to
        // stop that happening once there are a hundred and fifty of them is to
        // stop registering them by hand.
        rewritePages(wiki.resolve("pages.js"), geneSections(wiki));
        rewriteLanding(wiki.resolveSibling("index.html"), wiki);
    }

    private static String slug(Gene gene) {
        return gene.key().substring(gene.key().indexOf('.') + 1);
    }

    /** The page a gene lives on. Hyphens, to match the hand-written pages beside them. */
    private static String pageOf(Gene gene) {
        return "gene-" + slug(gene).replace('_', '-') + ".html";
    }

    // ------------------------------------------------------------------
    // pages.js
    // ------------------------------------------------------------------

    private static final String BEGIN = "        /* BEGIN generated by :common:bakeGeneWikiPages";
    private static final String END = "        /* END generated by :common:bakeGeneWikiPages */";

    /**
     * Replace the generated span of {@code pages.js} in place.
     *
     * <p>Hard rule 7 says a page is registered in {@code SECTIONS} and nowhere
     * else, and eighty-odd of them cannot be maintained by hand - so the tool
     * writes that part of the file. Everything outside the two markers is left
     * exactly as it was; a hand-written section can sit either side of them.
     */
    private static void rewritePages(Path pages, String sections) throws IOException {
        // Normalise on the way in. A checkout on Windows can leave this file
        // CRLF, and an anchor written with a bare newline then silently matches
        // nothing - which looks exactly like "the section is missing".
        String s = Files.readString(pages, StandardCharsets.UTF_8).replace("\r\n", "\n");
        String block = BEGIN + " - do not edit between the markers.\n"
                + "           One section per magical gene family, each led by its index page.\n"
                + "           Hand-written entries go OUTSIDE this span and are never touched. */\n"
                + sections
                + END + "\n";
        int i = s.indexOf(BEGIN);
        if (i < 0) {
            // First run: land it immediately after the magical-gene section, which
            // is where a reader looking for a magical gene is already looking.
            String anchor = "        {\n            title: \"Gameplay\",";
            int at = s.indexOf(anchor);
            if (at < 0) {
                throw new IllegalStateException("pages.js: no anchor to insert the generated span at");
            }
            s = s.substring(0, at) + block + s.substring(at);
        } else {
            int j = s.indexOf(END, i);
            if (j < 0) {
                throw new IllegalStateException("pages.js: BEGIN marker with no END");
            }
            s = s.substring(0, i) + block + s.substring(j + END.length() + 1);
        }
        Files.writeString(pages, s, StandardCharsets.UTF_8);
        System.out.println("rewrote the generated span of " + pages.getFileName());
    }

    /**
     * <b>Every gene page in the wiki, grouped by {@link GeneFamily}</b> - the
     * sidebar's gene sections, whole.
     *
     * <h2>Why the tool writes all of them and not only its own</h2>
     * It used to emit the eighty-odd data-driven genes and leave the built-ins
     * to five hand-written sections beside it. That gave the wiki one grouping
     * of the genes and the two gene editors another, which is a disagreement
     * with no upside; and it meant a gene with a page could quietly fail to be
     * registered, which is not a hypothetical - {@code PATN1} and {@code PATN2}
     * have never had one. So this reads the registry, not a list.
     *
     * <h2>Where the text and the views come from</h2>
     * <b>The page itself.</b> The sidebar label is the page's own {@code <h1>}
     * and the views are the {@code data-tab} panels it actually carries, so the
     * sidebar cannot promise a science tab that is not there and cannot call a
     * gene something its own heading does not. That is the same rule
     * {@code wiki/tools/sync-page-views.mjs} applies to every other page; this
     * simply applies it while it is already reading the file.
     *
     * <p>A gene with no page is skipped and named on stdout. That is the honest
     * outcome for a locus documented inside another gene's page - the leopard
     * complex's two modifiers - and it is loud enough to notice for one that was
     * merely forgotten.
     */
    private static String geneSections(Path wiki) throws IOException {
        StringBuilder sb = new StringBuilder();
        List<String> pageless = new ArrayList<>();

        for (GeneFamily family : GeneFamily.occupied()) {
            List<String> items = new ArrayList<>();

            // The family's own index page leads its section, where there is one.
            if (family.slug() != null) {
                Path index = wiki.resolve(family.slug() + ".html");
                items.add(item(family.slug() + ".html",
                        "All " + family.title().toLowerCase(Locale.ROOT),
                        "magical", viewsOf(index)));
            }

            for (Gene gene : membersForMenu(family)) {
                Path page = wiki.resolve(pageOf(gene));
                if (!Files.exists(page)) {
                    pageless.add(gene.key());
                    continue;
                }
                items.add(item(pageOf(gene), headingOf(page, gene.name()),
                        gene.isNatural() ? "natural" : "magical", viewsOf(page)));
            }
            if (items.isEmpty()) {
                continue;
            }
            sb.append("        {\n            title: \"").append(esc(family.label()))
                    .append("\",\n            items: [\n")
                    .append(String.join(",\n", items))
                    .append("\n            ]\n        },\n");
        }
        if (!pageless.isEmpty()) {
            System.out.println("  (no page of their own, so not listed: " + pageless + ")");
        }
        return sb.toString();
    }

    /**
     * A family's genes in the order the menu should offer them: <b>naturals in
     * paint order, magic alphabetically</b>.
     *
     * <p>Not a style choice either way. The natural loci are few and the order
     * the pipeline applies them in is the order they make sense in - extension
     * before agouti before the dilutions before the whites - and a reader
     * following the model wants that. There are eighty-odd magical genes and
     * nobody can find one by remembering where it paints.
     */
    private static List<Gene> membersForMenu(GeneFamily family) {
        List<Gene> genes = new ArrayList<>(family.members());
        if (!family.natural()) {
            genes.sort((a, b) -> a.name().compareToIgnoreCase(b.name()));
        }
        return genes;
    }

    private static String item(String href, String text, String kind, List<String> views) {
        StringBuilder v = new StringBuilder();
        for (int i = 0; i < views.size(); i++) {
            v.append(i == 0 ? "" : ",").append('"').append(views.get(i)).append('"');
        }
        return "                { href: \"" + href + "\", text: \"" + js(text)
                + "\", kind: \"" + kind + "\", views: [" + v + "] }";
    }

    /**
     * Escape for a <b>JavaScript string literal</b>, which is not the same job
     * as escaping for HTML and had been done with the HTML escaper. The sidebar
     * hands these to {@code createTextNode}, so an entity in one arrives on
     * screen as its own source: {@code &mdash;} rather than an em dash.
     */
    private static String js(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static final Pattern H1 = Pattern.compile("<h1>(.*?)</h1>", Pattern.DOTALL);
    private static final Pattern TAB = Pattern.compile("data-tab=\"([a-z]+)\"");

    /**
     * A page's own {@code <h1>} as plain text: tags stripped, entities decoded,
     * and any <b>subtitle after an em dash</b> dropped.
     *
     * <p>Several gene pages are headed "Sooty &mdash; the dark that lies on
     * top". That is a good heading and a bad sidebar entry: the sidebar is a
     * column of a hundred and sixty names being scanned for one of them, and
     * the half before the dash is the name. Everything after it is on the page.
     */
    private static String headingOf(Path page, String fallback) throws IOException {
        Matcher m = H1.matcher(Files.readString(page, StandardCharsets.UTF_8));
        if (!m.find()) {
            return fallback;
        }
        String text = decode(m.group(1).replaceAll("<[^>]*>", "")).trim();
        int dash = text.indexOf(" — ");
        if (dash > 0) {
            text = text.substring(0, dash).trim();
        }
        return text.isEmpty() ? fallback : text;
    }

    /** The handful of HTML entities the gene headings actually use. */
    private static String decode(String s) {
        return s.replace("&mdash;", "—").replace("&ndash;", "–")
                .replace("&rsquo;", "’").replace("&lsquo;", "‘")
                .replace("&eacute;", "é").replace("&hellip;", "…")
                .replace("&middot;", "·").replace("&times;", "×")
                .replace("&minus;", "−").replace("&quot;", "\"")
                .replace("&lt;", "<").replace("&gt;", ">")
                .replace("&amp;", "&");     // last, or it would double-decode
    }

    /**
     * The views a page has something for: its {@code data-tab} panels, in the
     * canonical order. A page with no panels at all is one continuous document
     * and is offered to the two audiences a gene page is always written for.
     */
    private static List<String> viewsOf(Path page) throws IOException {
        if (!Files.exists(page)) {
            return List.of("gameplay", "coding");
        }
        Set<String> found = new LinkedHashSet<>();
        Matcher m = TAB.matcher(Files.readString(page, StandardCharsets.UTF_8));
        while (m.find()) {
            found.add(m.group(1));
        }
        List<String> out = new ArrayList<>();
        for (String v : new String[]{"gameplay", "coding", "science"}) {
            if (found.contains(v)) {
                out.add(v);
            }
        }
        return out.isEmpty() ? List.of("gameplay", "coding") : out;
    }

    // ------------------------------------------------------------------
    // index.html - the landing page's gene cards
    // ------------------------------------------------------------------

    private static final String LAND_BEGIN =
            "    <!-- BEGIN generated by :common:bakeGeneWikiPages";
    private static final String LAND_END =
            "    <!-- END generated by :common:bakeGeneWikiPages -->";

    /**
     * <b>One card per gene on the landing page, grouped by family</b> - the same
     * grouping, in the same order, as the sidebar and as the two gene editors'
     * filter menu.
     *
     * <h2>A hand-written card always wins</h2>
     * The card bodies people wrote - the paragraph and the tag line - are
     * <b>harvested off the page and put back</b>, keyed by href. Only a gene
     * with no card yet gets a generated one, from its own blurb and allele
     * tokens. So this adds the hundred-odd genes nobody had time to write a
     * card for without flattening the thirty that somebody did, and editing one
     * of those by hand keeps working exactly as it did.
     *
     * <p>The card links to the gene's page and carries its baked icon where one
     * exists, which is every data-driven gene ({@code GeneIconTool} writes them
     * on a standard bay).
     */
    private static void rewriteLanding(Path landing, Path wiki) throws IOException {
        if (!Files.exists(landing)) {
            System.out.println("no " + landing + " - skipped the landing page");
            return;
        }
        String page = Files.readString(landing, StandardCharsets.UTF_8).replace("\r\n", "\n");
        Map<String, String> existing = harvestCards(page);

        StringBuilder body = new StringBuilder();
        body.append(LAND_BEGIN).append(" - do not edit between the markers.\n")
                .append("         One section per gene family, one card per gene. A card body written\n")
                .append("         by hand is harvested and put back; only a gene with no card gets a\n")
                .append("         generated one. See GeneWikiTool.rewriteLanding. -->\n");

        int generated = 0;
        for (GeneFamily family : GeneFamily.occupied()) {
            List<String> cards = new ArrayList<>();
            if (family.slug() != null) {
                cards.add(familyCard(family, existing.get("wiki/" + family.slug() + ".html")));
            }
            for (Gene gene : membersForMenu(family)) {
                if (!Files.exists(wiki.resolve(pageOf(gene)))) {
                    continue;
                }
                String kept = existing.get("wiki/" + pageOf(gene));
                if (kept == null) {
                    generated++;
                }
                cards.add(geneCard(gene, wiki, kept));
            }
            if (cards.isEmpty()) {
                continue;
            }
            body.append("\n    <div class=\"section-head\">\n        <h2>")
                    .append(esc(family.label())).append("</h2>\n        <p>")
                    .append(esc(family.lede())).append("</p>\n    </div>\n")
                    .append("    <div class=\"cards\">\n");
            for (String card : cards) {
                body.append(card);
            }
            body.append("    </div>\n");
        }
        body.append("\n").append(LAND_END).append("\n");

        int i = page.indexOf(LAND_BEGIN);
        String out;
        if (i < 0) {
            // First run: the gene cards replace whatever sits between the
            // "Natural genes" heading and the section after the magical one.
            int at = page.indexOf("    <div class=\"section-head\">\n        <h2>Natural genes</h2>");
            if (at < 0) {
                throw new IllegalStateException("index.html: no anchor to insert the gene cards at");
            }
            int after = page.indexOf("    <div class=\"section-head\">", magicalEnd(page));
            if (after < 0) {
                throw new IllegalStateException("index.html: no section after the gene cards");
            }
            out = page.substring(0, at) + body + page.substring(after);
        } else {
            int j = page.indexOf(LAND_END, i);
            if (j < 0) {
                throw new IllegalStateException("index.html: BEGIN marker with no END");
            }
            out = page.substring(0, i) + body + page.substring(j + LAND_END.length() + 1);
        }
        out = rewriteStats(out);
        Files.writeString(landing, out, StandardCharsets.UTF_8);
        System.out.println("rewrote the gene cards on " + landing.getFileName()
                + " (" + generated + " generated, " + existing.size() + " hand-written kept)");
    }

    private static final String STAT_BEGIN =
            "        <!-- BEGIN stats generated by :common:bakeGeneWikiPages";
    private static final String STAT_END =
            "        <!-- END stats generated by :common:bakeGeneWikiPages -->";

    /**
     * <b>The four numbers in the landing page's header.</b>
     *
     * <p>They were hand-written, and by the time anybody checked, three of them
     * had drifted by orders of magnitude - the gene count said 69 against a
     * registry of over a hundred and fifty. A derived number in prose is stale
     * the next time the code moves, and these four move every time a gene is
     * added. So they are read off the accessors that produce them:
     * {@code Genes.codeOrder().size()}, {@code Breeds.all().size()},
     * {@link GenotypeCatalog#totalGenotypes()} and {@link GenotypeCatalog#size()}.
     *
     * <p>The last of those <b>saturates</b>. The catalogue counts into a
     * {@code long} because callers index into it, and the distinct-looking
     * count passed {@link Long#MAX_VALUE} somewhere in the eighty-four magical
     * genes, so the honest thing to print is a floor rather than a figure.
     */
    private static String rewriteStats(String page) {
        int i = page.indexOf(STAT_BEGIN);
        int at;
        int end;
        if (i >= 0) {
            int j = page.indexOf(STAT_END, i);
            if (j < 0) {
                throw new IllegalStateException("index.html: stats BEGIN with no END");
            }
            at = i;
            end = j + STAT_END.length() + 1;
        } else {
            at = page.indexOf("        <div class=\"stats\">");
            if (at < 0) {
                return page;        // no header stats on this page; nothing to do
            }
            // The block's own closing tag, at its own indentation - not the
            // first </div> after it, which ends the first stat row.
            end = page.indexOf("\n        </div>\n", at);
            if (end < 0) {
                throw new IllegalStateException("index.html: unterminated stats block");
            }
            end += "\n        </div>\n".length();
            // and take the hand-written comment above it with us
            int comment = page.lastIndexOf("        <!--", at);
            if (comment >= 0 && page.indexOf("-->", comment) < at) {
                at = comment;
            }
        }

        long distinct = GenotypeCatalog.size();
        String block = STAT_BEGIN + " - do not edit between the markers.\n"
                + "             Four accessors, not four numbers somebody typed: three of these\n"
                + "             had drifted by orders of magnitude while they were prose. -->\n"
                + "        <div class=\"stats\">\n"
                + "            <div><span>" + Genes.codeOrder().size() + "</span><small>genes</small></div>\n"
                + "            <div><span>" + Breeds.all().size() + "</span><small>breeds</small></div>\n"
                + "            <div><span>" + power(GenotypeCatalog.totalGenotypes())
                + "</span><small>genotypes</small></div>\n"
                + "            <div><span>" + (distinct == Long.MAX_VALUE
                        ? "&gt;9&times;10<sup>18</sup>" : group(distinct))
                + "</span><small>visually distinct</small></div>\n"
                + "        </div>\n"
                + STAT_END + "\n";
        return page.substring(0, at) + block + page.substring(end);
    }

    /** A very large integer as {@code m&times;10<sup>e</sup>}, two significant figures. */
    private static String power(BigInteger n) {
        String digits = n.toString();
        int exponent = digits.length() - 1;
        String mantissa = digits.length() > 1
                ? digits.charAt(0) + "." + digits.charAt(1)
                : digits;
        return mantissa + "&times;10<sup>" + exponent + "</sup>";
    }

    private static String group(long n) {
        StringBuilder sb = new StringBuilder(Long.toString(n));
        for (int i = sb.length() - 3; i > 0; i -= 3) {
            sb.insert(i, ',');
        }
        return sb.toString();
    }

    /** Where the old hand-written magical-gene block ended, on the very first run. */
    private static int magicalEnd(String page) {
        int at = page.indexOf("<h2>Magical genes</h2>");
        return at < 0 ? 0 : at;
    }

    private static final Pattern CARD = Pattern.compile(
            "^[ \\t]*<a href=\"(wiki/gene[^\"]*\\.html)\" class=\"card[^\"]*\">\\n"
                    + "(.*?)^[ \\t]*</a>\\n",
            Pattern.DOTALL | Pattern.MULTILINE);

    /**
     * The <b>body</b> of every gene card already on the page, keyed by href -
     * the heading, the paragraph and the tag line somebody wrote, without the
     * anchor around them.
     *
     * <p>Only the body is kept. The anchor is rebuilt from the gene every time,
     * so the href, the natural / magical class and the icon are always what the
     * registry says and can never be a card that was moved between families and
     * kept the old colour.
     */
    private static Map<String, String> harvestCards(String page) {
        Map<String, String> out = new LinkedHashMap<>();
        Matcher m = CARD.matcher(page);
        while (m.find()) {
            out.put(m.group(1), reindent(m.group(2)));
        }
        return out;
    }

    /** Put a harvested body back on the page's own indentation. */
    private static String reindent(String body) {
        StringBuilder sb = new StringBuilder();
        for (String line : body.split("\n", -1)) {
            String trimmed = line.strip();
            if (trimmed.isEmpty()) {
                continue;
            }
            sb.append("            ").append(trimmed).append('\n');
        }
        return sb.toString();
    }

    /**
     * The anchor round a card body: href, kind, and the baked icon if there is
     * one.
     *
     * <p>The two icon questions are deliberately different. <b>Is there an
     * icon</b> decides the class, and a body carrying its own {@code <img>}
     * counts - the seven family cards each picked a representative gene's bake
     * by hand and keep it. <b>Should one be added</b> is narrower: only when the
     * body has not got one already, or a card would grow a second icon every
     * time this ran.
     */
    private static String card(String href, String kind, String icon, String body) {
        boolean bodyHasIcon = body.contains("card-icon");
        boolean anyIcon = icon != null || bodyHasIcon;
        return "        <a href=\"" + href + "\" class=\"card " + kind
                + (anyIcon ? " card-iconed" : "") + "\">\n"
                + (icon != null && !bodyHasIcon
                        ? "            <img class=\"card-icon\" src=\"" + icon
                                + "\" alt=\"\" width=\"120\" loading=\"lazy\">\n"
                        : "")
                + body
                + "        </a>\n";
    }

    private static String familyCard(GeneFamily family, String body) {
        return card("wiki/" + family.slug() + ".html", "magical", null,
                body != null ? body
                        : "            <h3>All " + esc(family.title().toLowerCase(Locale.ROOT))
                                + "</h3>\n            <p>" + esc(family.lede())
                                + "</p>\n            <span class=\"tag\">index</span>\n");
    }

    /**
     * A card for a gene nobody wrote one for: its own blurb, its alleles, and
     * its baked icon if it has one. Deliberately thin - the point of a card is
     * to be a door to the page, and the page has everything.
     */
    private static String geneCard(Gene gene, Path wiki, String body) {
        String icon = Files.exists(wiki.resolve("assets/gene-icons/" + slug(gene) + ".png"))
                ? "wiki/assets/gene-icons/" + slug(gene) + ".png"
                : null;
        if (body == null) {
            List<String> tokens = new ArrayList<>();
            for (Allele a : gene.alleles()) {
                tokens.add(a.token());
            }
            String tag = tokens.size() > 4 ? tokens.size() + " alleles" : String.join(" / ", tokens);
            String blurb = gene.description();
            body = "            <h3>" + esc(gene.name()) + "</h3>\n"
                    + (blurb == null || blurb.isEmpty()
                            ? "" : "            <p>" + esc(blurb) + "</p>\n")
                    + "            <span class=\"tag\">" + esc(tag) + "</span>\n";
        }
        return card("wiki/" + pageOf(gene), gene.isNatural() ? "natural" : "magical", icon, body);
    }

    // ------------------------------------------------------------------
    // The family index
    // ------------------------------------------------------------------

    private static String familyPage(GeneFamily family, List<SpecGene> genes) {
        StringBuilder sb = new StringBuilder();
        head(sb, family.title());
        sb.append("<p class=\"eyebrow magical\">Magical genes <span class=\"sep\">/</span> ")
                .append(genes.size()).append(" in this family</p>\n\n");
        sb.append("<h1>").append(esc(family.title())).append("</h1>\n\n");
        sb.append("<p class=\"lede\">\n    ").append(esc(family.lede())).append("\n</p>\n\n");
        sb.append("<p class=\"note\">\n    An index. <strong>Each of these has its own page</strong>"
                + " - that is where the\n    inheritance table, the gene carrot and how you actually"
                + " come by one live.\n    The picture beside each name is that gene on a standard"
                + " bay, baked through the\n    real coat pipeline rather than drawn.\n</p>\n\n");

        sb.append("<section class=\"tab-panel\" data-tab=\"gameplay\">\n\n");
        for (SpecGene gene : genes) {
            sb.append("<h2 id=\"").append(slug(gene).replace('_', '-')).append("\"><a href=\"")
                    .append(pageOf(gene)).append("\">").append(esc(gene.name())).append("</a></h2>\n\n");
            sb.append("<div class=\"gene-card\">\n");
            sb.append("<a href=\"").append(pageOf(gene)).append("\">")
                    .append("<img class=\"gene-card-icon\" src=\"assets/gene-icons/").append(slug(gene))
                    .append(".png\" alt=\"").append(esc(gene.name()))
                    .append(" on a bay horse\" width=\"150\" loading=\"lazy\"></a>\n");
            sb.append("<div class=\"gene-card-body\">\n");
            if (!gene.spec().blurb().isBlank()) {
                sb.append("<p>").append(esc(gene.spec().blurb())).append("</p>\n");
            }
            sb.append("<p class=\"gene-card-alleles\">").append(alleleList(gene))
                    .append(" &middot; <a href=\"").append(pageOf(gene))
                    .append("\">full page</a></p>\n");
            sb.append("</div>\n</div>\n\n");
        }
        sb.append("</section>\n\n");

        sb.append("<section class=\"tab-panel\" data-tab=\"coding\">\n\n");
        sb.append("<h2 id=\"files\">The files</h2>\n\n");
        sb.append("<p>\n    Each of these is a JSON file in\n    "
                + "<code>common/src/main/resources/horsegenetics/genes/</code>, listed in the\n    "
                + "<code>index.json</code> beside them and loaded by <code>Genes</code>' class\n    "
                + "initialiser. None is a Java class; see\n    "
                + "<a href=\"gene-format.html\">the gene file format</a> for what the masks and "
                + "ops mean.\n</p>\n\n");
        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n<thead><tr>")
                .append("<th>Gene</th><th>File</th><th>Priority</th>")
                .append("<th>Masks and ops it uses</th></tr></thead>\n<tbody>\n");
        for (SpecGene gene : genes) {
            sb.append("<tr><td><a href=\"").append(pageOf(gene)).append("\">")
                    .append(esc(gene.name())).append("</a></td>")
                    .append("<td><code>").append(slug(gene)).append(".json</code></td>")
                    .append("<td>").append(gene.priority()).append("</td>")
                    .append("<td>").append(esc(String.join(", ", vocabulary(gene)))).append("</td></tr>\n");
        }
        sb.append("</tbody>\n</table>\n</div>\n\n</section>\n\n");
        foot(sb);
        return sb.toString();
    }

    // ------------------------------------------------------------------
    // One gene, one page
    // ------------------------------------------------------------------

    private static String genePage(SpecGene gene, GeneFamily family) {
        String slug = slug(gene);
        StringBuilder sb = new StringBuilder();
        head(sb, gene.name());

        sb.append("<p class=\"eyebrow magical\">Magical gene <span class=\"sep\">/</span> ")
                .append("<a href=\"").append(family.slug()).append(".html\">")
                .append(esc(family.title().toLowerCase(Locale.ROOT))).append("</a></p>\n\n");
        sb.append("<h1>").append(esc(gene.name())).append("</h1>\n\n");
        if (!gene.spec().blurb().isBlank()) {
            sb.append("<p class=\"lede\">\n    ").append(esc(gene.spec().blurb())).append("\n</p>\n\n");
        }

        // ---- gameplay -------------------------------------------------
        sb.append("<section class=\"tab-panel\" data-tab=\"gameplay\">\n\n");
        sb.append("<div class=\"gene-preview\" data-gene=\"").append(gene.key()).append("\"></div>\n\n");

        sb.append(outcomeSummary(gene));

        sb.append("<h2 id=\"inheritance\">What you can get</h2>\n\n");
        sb.append("<div class=\"gene-inheritance\" data-gene=\"").append(gene.key())
                .append("\"></div>\n\n");

        sb.append(acquisition(gene));

        sb.append("<h2 id=\"carrot\">Its gene carrot</h2>\n\n");
        sb.append("<!-- The recipe, read off the mod at run time - the rarity tier is the\n"
                + "     recipe's price, and a price written into eighty pages goes stale\n"
                + "     silently. See wiki/gene-carrot/gene-carrot.js. -->\n\n");
        sb.append("<div class=\"gene-carrot\" data-gene=\"").append(gene.key()).append("\"></div>\n\n");
        sb.append("</section>\n\n");

        // ---- coding ---------------------------------------------------
        sb.append("<section class=\"tab-panel\" data-tab=\"coding\">\n\n");
        sb.append("<h2 id=\"file\">The file</h2>\n\n");
        sb.append("<p>\n    <code>common/src/main/resources/horsegenetics/genes/").append(slug)
                .append(".json</code> &mdash; a\n    <a href=\"gene-format.html\">data-driven gene</a>,"
                        + " not a Java class. It is listed in the\n    <code>index.json</code> beside"
                        + " it and registered by <code>Genes</code>' class\n    initialiser at"
                        + " startup.\n</p>\n\n");

        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n<tbody>\n");
        sb.append("<tr><th>Key</th><td><code>").append(gene.key()).append("</code></td></tr>\n");
        sb.append("<tr><th>Phase</th><td>magical &mdash; it adds signed colour in phase 3, "
                + "after the pigment has resolved</td></tr>\n");
        sb.append("<tr><th>Priority</th><td>").append(gene.priority())
                .append(" &mdash; where it sits in the one <code>(priority, key)</code> paint "
                        + "order</td></tr>\n");
        sb.append("<tr><th>Alleles</th><td>").append(alleleList(gene)).append("</td></tr>\n");
        sb.append("<tr><th>Varies per horse</th><td>")
                .append(gene.spec().knobs().isEmpty()
                        ? "no &mdash; every horse carrying it looks the same"
                        : gene.spec().knobs().size() + " value"
                                + (gene.spec().knobs().size() == 1 ? "" : "s")
                                + " drawn once off the expressing allele copy, so a foal that "
                                + "inherits the copy inherits the look")
                .append("</td></tr>\n");
        sb.append("<tr><th>Built from</th><td>")
                .append(esc(String.join(", ", vocabulary(gene)))).append("</td></tr>\n");
        sb.append("</tbody>\n</table>\n</div>\n\n");

        sb.append(layers(gene));
        sb.append("</section>\n\n");
        foot(sb);
        return sb.toString();
    }

    /**
     * <b>What the gene can come out as, on the gameplay tab</b>: the outcome
     * names and the allele combinations that produce them, and no more.
     *
     * <p>The prose describing each outcome used to be here, and it is the wrong
     * tab for it. These descriptions came out of the source documents part by
     * part - "from the poll down through the orbits and the nasal region to the
     * muzzle, bounded along the cheekbone and the jaw" - which is a
     * specification of how the thing is drawn, not what a player wants to read
     * before going to look for one. It is on the coding tab now, next to the
     * layers that draw it, where the two halves of the same statement can be
     * read together. The gameplay tab keeps the picture, the names, the odds
     * and the carrot.
     */
    private static String outcomeSummary(SpecGene gene) {
        StringBuilder sb = new StringBuilder("<h2 id=\"outcomes\">What it can come out as</h2>\n\n");
        sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n")
                .append("<thead><tr><th>Outcome</th><th>Carrying</th></tr></thead>\n<tbody>\n");
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            List<String> combos = new ArrayList<>();
            for (String c : e.combinations()) {
                combos.add("<code>" + esc(c) + "</code>");
            }
            sb.append("<tr><th>").append(esc(e.name())).append("</th><td>")
                    .append(combos.isEmpty()
                            ? "anything else"
                            : String.join(" &middot; ", combos))
                    .append("</td></tr>\n");
        }
        sb.append("</tbody>\n</table>\n</div>\n\n");
        sb.append("<p class=\"muted\">\n    How each one is actually drawn - region by region,"
                + " and the layers it is built from -\n    is on the"
                + " <a href=\"#layers\">coding tab</a>.\n</p>\n\n");
        return sb.toString();
    }

    /**
     * How a player actually comes by the gene.
     *
     * <p>The founder table is the one acquisition fact with no run-time widget
     * behind it, so it is baked - hence the gene files' row in
     * {@code CLAUDE.md}'s regeneration table. The rarity tier and the carrot are
     * deliberately <i>not</i> here; the card below reads those off the mod.
     */
    private static String acquisition(SpecGene gene) {
        StringBuilder sb = new StringBuilder();
        sb.append("<h2 id=\"finding\">Finding one</h2>\n\n");

        double showing = 0;
        List<String> rows = new ArrayList<>();
        for (GeneSpec.FounderWeight w : gene.spec().founders()) {
            if (w.percent() <= 0) {
                continue;
            }
            GeneSpec.ExpressionSpec e = expressionFor(gene, w.combination());
            boolean shows = e != null && !e.wildType();
            if (shows) {
                showing += w.percent();
            }
            rows.add("<tr><td><code>" + esc(w.combination()) + "</code></td><td>"
                    + (e == null ? "&mdash;" : esc(e.name())) + "</td><td>"
                    + odds(w.percent()) + "</td></tr>");
        }

        if (showing <= 0) {
            sb.append("<p>\n    <strong>No wild horse carries it.</strong> Every copy in the world"
                    + " came from a\n    gene carrot or a splice; there is nothing to go looking"
                    + " for.\n</p>\n\n");
        } else {
            sb.append("<p>\n    About <strong>").append(oneIn(showing))
                    .append("</strong> wild horses is born showing this. That is the whole of the"
                            + "\n    supply: catch one, or make one with the carrot below. Breeds set"
                            + " their own\n    pools and a breed built around this gene will carry it"
                            + " far more often than\n    the wild population does.\n</p>\n\n");
        }

        if (!rows.isEmpty()) {
            sb.append("<div class=\"table-wrap\">\n<table class=\"facts\">\n")
                    .append("<thead><tr><th>Wild pair</th><th>Shows as</th><th>How often</th>")
                    .append("</tr></thead>\n<tbody>\n")
                    .append(String.join("\n", rows))
                    .append("\n</tbody>\n</table>\n</div>\n\n");
        }
        return sb.toString();
    }

    private static GeneSpec.ExpressionSpec expressionFor(SpecGene gene, String combination) {
        GeneSpec.ExpressionSpec catchAll = null;
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            if (e.isCatchAll()) {
                catchAll = e;
            } else if (e.combinations().contains(combination)) {
                return e;
            }
        }
        return catchAll;
    }

    /**
     * A percentage as something a player can picture. Past a half the "1 in N"
     * form stops helping - "99.92% - 1 in 1" is worse than the percentage on its
     * own - so the common case just says the number.
     */
    private static String odds(double percent) {
        if (percent > 50) {
            return trim(percent) + "%";
        }
        return String.format(Locale.ROOT, "%s%% &mdash; %s", trim(percent), oneIn(percent));
    }

    private static String oneIn(double percent) {
        if (percent >= 100) {
            return "every horse";
        }
        long n = Math.round(100.0 / percent);
        return "1 in " + String.format(Locale.ROOT, "%,d", n);
    }

    private static String trim(double v) {
        String s = String.format(Locale.ROOT, "%.4f", v);
        while (s.contains(".") && (s.endsWith("0") || s.endsWith("."))) {
            s = s.substring(0, s.length() - 1);
        }
        return s;
    }

    private static String layers(SpecGene gene) {
        StringBuilder sb = new StringBuilder("<h2 id=\"layers\">What it paints</h2>\n\n");
        sb.append("<p>\n    Each outcome, described the way the gene file describes it, and then"
                + " the\n    layers that draw it in the order they are painted. The prose is the"
                + " part\n    a reader checks a bake against; the list underneath is what the"
                + " engine\n    actually did.\n</p>\n\n");
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            if (e.layers().isEmpty() && e.description().isBlank()) {
                continue;
            }
            sb.append("<h3>").append(esc(e.name())).append("</h3>\n\n");
            if (!e.description().isBlank()) {
                sb.append("<p>").append(esc(e.description())).append("</p>\n\n");
            }
            if (e.layers().isEmpty()) {
                sb.append("<p class=\"muted\">Paints nothing.</p>\n\n");
                continue;
            }
            sb.append("<ol>\n");
            for (GeneSpec.Layer layer : e.layers()) {
                sb.append("<li>").append(esc(layer.name()));
                List<String> masks = new ArrayList<>();
                for (GeneSpec.Mask mask : layer.masks()) {
                    masks.add("<code>" + mask.type() + (mask.invert() ? " inverted" : "") + "</code>");
                }
                sb.append(" &mdash; ").append(String.join(" &times; ", masks))
                        .append(", painted with <code>").append(layer.op().type()).append("</code>");
                if (layer.emissive()) {
                    sb.append(", and it <strong>glows</strong>");
                }
                sb.append("</li>\n");
            }
            sb.append("</ol>\n\n");
        }
        return sb.toString();
    }

    // ------------------------------------------------------------------

    private static String alleleList(SpecGene gene) {
        List<String> tokens = new ArrayList<>();
        for (Allele a : gene.alleles()) {
            tokens.add("<code>" + esc(a.token()) + "</code>");
        }
        return String.join(" &middot; ", tokens);
    }

    private static List<String> vocabulary(SpecGene gene) {
        Set<String> out = new LinkedHashSet<>();
        for (GeneSpec.ExpressionSpec e : gene.spec().expressions()) {
            for (GeneSpec.Layer layer : e.layers()) {
                for (GeneSpec.Mask mask : layer.masks()) {
                    out.add(mask.type().name());
                }
                out.add(layer.op().type().name());
                if (layer.emissive()) {
                    out.add("emissive");
                }
            }
        }
        List<String> sorted = new ArrayList<>(out);
        sorted.sort(String::compareTo);
        return sorted;
    }

    private static void head(StringBuilder sb, String title) {
        sb.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n").append(GENERATED).append('\n')
                .append("<meta charset=\"UTF-8\">\n")
                .append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n")
                .append("<title>").append(esc(title)).append(" &middot; Horse Genetics Wiki</title>\n")
                .append("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/")
                .append("prism/1.29.0/themes/prism-tomorrow.min.css\">\n")
                .append("<link rel=\"stylesheet\" href=\"styles.css\">\n")
                .append("<script defer src=\"pages.js\"></script>\n")
                .append("<script defer src=\"tabs.js\"></script>\n")
                .append("<script defer src=\"nav.js\"></script>\n")
                .append("<script defer src=\"search.js\"></script>\n")
                .append("</head>\n<body>\n<main class=\"content\">\n<article class=\"doc\">\n\n");
    }

    private static void foot(StringBuilder sb) {
        sb.append("</article>\n</main>\n")
                .append("<script defer src=\"gene-preview/gene-preview.js\"></script>\n")
                .append("<script defer src=\"gene-inheritance/gene-inheritance.js\"></script>\n")
                .append("<script defer src=\"gene-carrot/gene-carrot.js\"></script>\n")
                .append("</body>\n</html>\n");
    }

    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
