package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.genetics.AllelePair;
import com.example.horsegenetics.common.genetics.Expression;
import com.example.horsegenetics.common.genetics.Gene;
import com.example.horsegenetics.common.genetics.GeneFamily;
import com.example.horsegenetics.common.genetics.Genes;
import com.example.horsegenetics.common.genetics.GenotypeCatalog;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * <b>Every outcome every gene can produce, on one page</b>: the table inside
 * {@code wiki/gene-census.html}.
 *
 * <h2>Why it is baked and not written</h2>
 * It is one row per <i>allele presentation</i> - a distinct {@link Expression}
 * of one gene, with every canonical {@link AllelePair} that lands on it - across
 * the whole registry. That is thousands of rows over hundreds of genes, and
 * every word in them is already written down in the gene's own file, in the
 * words the game shows. A hand-written census would be a second copy of the
 * registry that goes stale the first time an outcome is reworded, and nobody
 * would notice: a census is exactly the kind of page a reader trusts without
 * checking. So the registry writes it. Re-run
 * {@code ./gradlew :common:bakeGeneCensus} after any gene changes.
 *
 * <h2>Why it counts what marking-facts.json refuses to</h2>
 * {@code MarkingFactsTool} skips two things on purpose, because it exists to
 * feed the breed designer's markings filters and a filter for "a horse that
 * looks like nothing happened" is not a marking: it skips genes that
 * {@link Gene#affectsCoat() paint nothing}, and it skips
 * {@link Expression#wildType() wild-type} combinations. This page keeps both,
 * because it is a <b>census</b> and not a picker. The wild type is the row that
 * tells a breed author what the population baseline at a locus actually is, and
 * is the answer to "why does my horse show nothing"; and the loci that change no
 * pixel - sex, diet, fireproof, milk, the health genes - are the ones a reader is
 * least able to find any other way, because they have no icon to recognise them
 * by. A gene with no coat and no wild type would appear on neither list.
 *
 * <h2>It is written to be read by a machine</h2>
 * The stated purpose is that somebody designing a breed or a gene can hand the
 * whole page to an AI and ask it questions. That is why the rows are baked into
 * the HTML rather than fetched or built by script - an assistant reads the
 * source, and a table assembled at run time is invisible to it - and why the
 * page is one flat semantic table with no tab panels to hide half of it. The
 * machine-readable <i>sources</i> are still the gene files themselves,
 * {@code common/src/main/resources/horsegenetics/genes/*.json}.
 *
 * <p>Arg 0 is the wiki directory - the tool needs it for two things: the page it
 * splices, and which gene pages exist on disk, since a gene name is only
 * hyperlinked when there is somewhere for the link to go (the thirteen eye loci
 * have no page of their own).
 */
public final class GeneCensusTool {

    private static final String BEGIN =
            "<!-- BEGIN generated by :common:bakeGeneCensus - do not edit between the markers -->";
    private static final String END = "<!-- END generated -->";

    private GeneCensusTool() {
    }

    public static void main(String[] args) throws IOException {
        Path wiki = Path.of(args.length > 0 ? args[0] : "wiki");
        Path page = Files.isDirectory(wiki) ? wiki.resolve("gene-census.html") : wiki;
        Path dir = page.toAbsolutePath().getParent();

        StringBuilder rows = new StringBuilder(1 << 20);
        int presentations = 0;
        int genes = 0;

        for (Gene gene : Genes.codeOrder()) {
            // Group the pairs by outcome, in encounter order. allPairsOf has
            // already dropped the combinations no horse could carry and put the
            // population's baseline first, so the first group is the one a wild
            // horse most likely has.
            Map<String, List<AllelePair>> byExpression = new LinkedHashMap<>();
            Map<String, Expression> expressionById = new LinkedHashMap<>();
            for (AllelePair pair : GenotypeCatalog.allPairsOf(gene)) {
                Expression e = gene.expressionOf(pair);
                if (e == null) {
                    // Not fatal: a gene whose table has a hole is a bug in that
                    // gene, not a reason for the whole census to fail to bake.
                    System.out.println("warning: " + gene.key() + " has no expression for "
                            + pair.toTokens() + " - row skipped");
                    continue;
                }
                byExpression.computeIfAbsent(e.id(), k -> new ArrayList<>()).add(pair);
                expressionById.put(e.id(), e);
            }
            if (byExpression.isEmpty()) {
                continue;
            }
            genes++;

            String name = esc(gene.name());
            String href = pageOf(gene);
            String geneCell = Files.exists(dir.resolve(href))
                    ? "<a href=\"" + href + "\">" + name + "</a>"
                    : name;
            String kind = gene.isNatural() ? "Natural" : "Magical";
            String family = esc(GeneFamily.of(gene).title());

            for (Map.Entry<String, List<AllelePair>> entry : byExpression.entrySet()) {
                Expression e = expressionById.get(entry.getKey());
                List<String> chips = new ArrayList<>();
                for (AllelePair pair : entry.getValue()) {
                    chips.add("<code>" + esc(pair.toTokens()) + "</code>");
                }
                rows.append("<tr>\n")
                        .append("<td class=\"cs-pairs\">").append(String.join(" &middot; ", chips))
                        .append("</td>\n")
                        .append("<td class=\"cs-gene\">").append(geneCell).append("</td>\n")
                        .append("<td class=\"cs-kind\">").append(kind).append("</td>\n")
                        .append("<td class=\"cs-family\">").append(family).append("</td>\n")
                        .append("<td class=\"cs-pres\">").append(esc(e.name())).append("</td>\n")
                        .append("<td class=\"cs-does\">").append(esc(e.description())).append("</td>\n")
                        .append("</tr>\n");
                presentations++;
            }
        }

        StringBuilder block = new StringBuilder(rows.length() + 2048);
        block.append(BEGIN).append("\n")
                .append("<p class=\"cs-summary\">").append(presentations)
                .append(" presentations across ").append(genes)
                .append(" genes.</p>\n")
                .append("<div class=\"table-wrap\">\n")
                .append("<table id=\"census\">\n")
                .append("<thead>\n<tr>\n")
                .append("<th scope=\"col\" data-sort=\"pairs\">Allele pair(s)</th>\n")
                .append("<th scope=\"col\" data-sort=\"gene\">Gene</th>\n")
                .append("<th scope=\"col\" data-sort=\"kind\">Kind</th>\n")
                .append("<th scope=\"col\" data-sort=\"family\">Category</th>\n")
                .append("<th scope=\"col\" data-sort=\"pres\">Presentation</th>\n")
                .append("<th scope=\"col\" data-sort=\"does\">What it does</th>\n")
                .append("</tr>\n</thead>\n")
                .append("<tbody>\n").append(rows).append("</tbody>\n")
                .append("</table>\n</div>\n")
                .append(END).append("\n");

        // Normalise on the way in: a checkout on Windows can leave the page
        // CRLF, and then a marker written with a bare newline matches nothing -
        // which looks exactly like "the markers are missing".
        String s = Files.readString(page, StandardCharsets.UTF_8).replace("\r\n", "\n");
        int i = s.indexOf(BEGIN);
        if (i < 0) {
            throw new IllegalStateException("gene-census.html: no BEGIN marker to write between");
        }
        int j = s.indexOf(END, i);
        if (j < 0) {
            throw new IllegalStateException("gene-census.html: BEGIN marker with no END");
        }
        s = s.substring(0, i) + block + s.substring(j + END.length() + 1);
        Files.writeString(page, s, StandardCharsets.UTF_8);
        System.out.println("wrote " + presentations + " presentations across " + genes
                + " genes to " + page.toAbsolutePath());
    }

    /** The page a gene lives on, as {@code GeneWikiTool} names it. */
    private static String pageOf(Gene gene) {
        String slug = gene.key().substring(gene.key().indexOf('.') + 1);
        return "gene-" + slug.replace('_', '-') + ".html";
    }

    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
