package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.SeededRng;
import com.example.horsegenetics.common.coat.pattern.CoatBuildContext;
import com.example.horsegenetics.common.coat.pattern.ColorField;
import com.example.horsegenetics.common.coat.pattern.PigmentField;
import com.example.horsegenetics.common.coat.pattern.SpecPainter;
import com.example.horsegenetics.common.coat.pattern.SvgPath;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Part;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Skin;
import com.example.horsegenetics.common.genetics.Allele;
import com.example.horsegenetics.common.genetics.AllelePair;
import com.example.horsegenetics.common.genetics.Epigenome;
import com.example.horsegenetics.common.genetics.Genotype;
import com.example.horsegenetics.common.genetics.epi.EpiRoll;

import java.io.IOException;
import com.example.horsegenetics.common.coat.pattern.CoatTextureComposer;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Writes the <b>parity fixtures</b> the gene creator checks itself against.
 *
 * <p>The creator previews a gene by running a JavaScript twin of
 * {@link SpecPainter}. A twin can drift, and a drifted twin is worse than no
 * preview at all - it shows a horse the game will not breed, convincingly. So
 * this tool bakes a set of example genes through the <b>real</b> Java engine and
 * records what it got; {@code wiki/gene-creator/tools/check-parity.mjs} runs the
 * same specs through the JavaScript and compares.
 *
 * <p>What it records per case: every knob the horse drew (which checks the
 * {@code java.util.Random} port as much as the painter), and the pigment or
 * colour at a spread of probe texels. Probes rather than a whole-sheet hash
 * because a mismatch should say <i>which texel on which part</i>, not just
 * "different".
 *
 * <p>{@code ./gradlew :common:bakeSpecFixtures}
 */
public final class SpecFixtureTool {

    /** Example genes to bake, from {@code main/resources/horsegenetics/example-genes/}. */
    private static final String[] SPECS = {"silver.json", "dun.json", "tobiano.json", "aurora.json", "prismatic.json"};

    /** Preview seeds - the same numbers the creator's seed box defaults to. */
    private static final long[] SEEDS = {1L, 7L, 21L};

    private static final Part[] PROBE_PARTS = {
            Part.BODY, Part.NECK, Part.HEAD, Part.MANE, Part.TAIL,
            Part.LEFT_FRONT_LEG, Part.RIGHT_HIND_LEG, Part.LEFT_EAR
    };

    private SpecFixtureTool() {}

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "wiki/gene-creator/fixtures/expected.json");
        Files.createDirectories(out.getParent());

        StringBuilder json = new StringBuilder();
        json.append("{\n  \"note\": \"GENERATED by :common:bakeSpecFixtures - do not hand-edit.\",\n");
        json.append(schemaSection());
        json.append("  \"cases\": [\n");

        List<String> cases = new ArrayList<>();
        for (String file : SPECS) {
            GeneSpec spec = GeneSpecParser.parse(read(file), file);
            SpecGene gene = new SpecGene(spec);
            for (long seed : SEEDS) {
                for (int dose : new int[]{1, 2}) {
                    for (Skin skin : Skin.values()) {
                        cases.add(bake(gene, file, seed, dose, skin));
                    }
                }
            }
        }
        json.append(String.join(",\n", cases));
        json.append("\n  ]\n}\n");
        Files.writeString(out, json.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + cases.size() + " parity cases to " + out.toAbsolutePath());

        // The same fixtures again as a classic script, so the creator can run
        // the parity check on itself when it boots. It cannot read the .json:
        // under file:// a fetch of a sibling file is blocked, which is the same
        // reason the textures and the examples are inlined.
        Path script = out.resolveSibling("expected.js");
        Files.writeString(script, """
                // GENERATED by :common:bakeSpecFixtures - do not hand-edit.
                // The twin of expected.json, as a classic script: the creator runs
                // js/parity.js against this on boot, and a file:// page cannot fetch
                // the .json sitting next to it.
                window.HG = window.HG || {};
                window.HG.fixtures =\s""" + json.toString().stripTrailing() + ";\n",
                StandardCharsets.UTF_8);
        System.out.println("wrote " + script.toAbsolutePath());
    }

    /**
     * The schema's defaults, so the creator can prove its mirror still matches.
     * This is not paranoia: the creator omits any setting equal to its default,
     * so a default that differs between the two writes a file that plays
     * differently from how it previewed - silently, and only for the settings
     * you left alone.
     */
    private static String schemaSection() {
        StringBuilder sb = new StringBuilder("  \"schema\": {\n    \"masks\": {");
        boolean first = true;
        for (GeneSpec.MaskType type : GeneSpec.MaskType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": ")
                    .append(params(SpecSchema.maskParams(type)));
            first = false;
        }
        sb.append("\n    },\n    \"ops\": {");
        first = true;
        for (GeneSpec.OpType type : GeneSpec.OpType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": { \"phase\": \"")
                    .append(type.isNatural() ? "natural" : "magical").append("\", \"params\": ")
                    .append(params(SpecSchema.opParams(type))).append(" }");
            first = false;
        }
        sb.append("\n    },\n    \"effects\": {");
        first = true;
        for (AbilityType type : AbilityType.all()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type.name()).append("\": ")
                    .append(abilityParams(type.params()));
            first = false;
        }
        sb.append("\n    },\n    \"conditionFlags\": [");
        for (int i = 0; i < AbilityType.CONDITION_FLAGS.size(); i++) {
            sb.append(i > 0 ? ", " : "").append("\"").append(AbilityType.CONDITION_FLAGS.get(i)).append("\"");
        }
        sb.append("],\n");
        // A shared CONSTANT rather than a schema parameter, and so invisible to
        // the parameter comparison above. It still has to match, and the probe
        // cases cannot be relied on to notice: they sample four texels per part,
        // and one sub-segment more or less on a curve moves the line by a
        // fraction of a texel. Compared directly, like the condition flags.
        sb.append("    \"pathCurveSamples\": ").append(SpecSchema.PATH_CURVE_SAMPLES)
                .append(",\n");
        sb.append(composerSection());
        sb.append(svgSection());
        sb.append(pathSection());
        sb.append(geometrySection());
        sb.append("  },\n");
        return sb.toString();
    }

    /**
     * The <b>composer's arithmetic</b>, as answer tables.
     *
     * <p>{@code check-parity.mjs} runs {@code restrict} and {@code tint} and
     * never runs {@code compose}, so everything in the creator's composite
     * mirror - the phase-2 alpha ramp, the phase-3a shadow lift, the final
     * multiply - had never been compared against anything. That is the hole
     * known-gaps gap 50 lived in: the mirror kept an {@code rgb == 0} equality
     * for months after the game replaced it with a ramp, the equality stopped
     * matching anything at all when the gradient's black corner moved off
     * {@code #000000}, and the creator quietly drew every dark coat at full
     * opacity.
     *
     * <p>The composite itself is not comparable here - it needs the gradient
     * and the template, and the Node harness has no image decoder. The
     * arithmetic is, because both functions are pure functions of ints, and the
     * arithmetic is where the drift was. The inputs below are chosen to sit on
     * both sides of every threshold: pure black, the shipped chart's actual
     * black, either side of NEAR_BLACK, and an ordinary coat colour.
     */
    private static String composerSection() {
        int[] probes = {0x000000, 0x0C0C0C, 0x161515, 0x2F2F2F, 0x303030, 0x9B4A28, 0xFFFFFF};
        StringBuilder sb = new StringBuilder("    \"composer\": {\n      \"nearBlackAlpha\": {");
        for (int i = 0; i < probes.length; i++) {
            sb.append(i > 0 ? ", " : " ").append("\"").append(hex(probes[i])).append("\": ")
                    .append(CoatTextureComposer.nearBlackAlphaFor(probes[i]));
        }
        sb.append(" },\n      \"shadowFloor\": ").append(CoatTextureComposer.shadowFloor());
        sb.append(",\n      \"liftShadows\": {");
        for (int i = 0; i < probes.length; i++) {
            int lifted = CoatTextureComposer.liftedForParity(probes[i]);
            sb.append(i > 0 ? ", " : " ").append("\"").append(hex(probes[i])).append("\": \"")
                    .append(hex(lifted)).append("\"");
        }
        sb.append(" }\n    },\n");
        return sb.toString();
    }

    /**
     * The <b>posed mesh</b>, as an answer table.
     *
     * <p>This is what closes known-gaps gap 100. {@code HorseSkinGeometry.posed} and
     * {@code posedNormal} walk the raw cuboid rather than its bounding box,
     * and the browser needs the same walk to draw a horse whose neck is
     * pitched. For a while that arithmetic existed <b>twice</b> - here, and
     * again in the creator's {@code model3d.js} - in two languages, in two
     * files that were not obviously a pair, with nothing comparing them. A
     * change to how a part is posed could reach the baked icons and not the
     * browser preview, or the reverse, and the symptom would be a wiki quietly
     * drawing a slightly different horse from the one the game breeds.
     *
     * <p>The creator's copy now lives in {@code geometry.js}, beside the rest
     * of its port of this class, and this table is what holds the two
     * together.
     *
     * <p><b>Corners alone would not do it.</b> A corner is a fraction of 0 or
     * 1 on both axes, and several ways of getting the axis pairing wrong agree
     * at the corners and disagree everywhere else - which is the exact shape of
     * the UV swap that once hid behind a stale fixture. So the probes include
     * both face centres and an off-centre point with no symmetry to it, and
     * they cover every part of both skins: a baby horse is not a scaled adult.
     */
    private static String geometrySection() {
        double[][] probes = {{0, 0}, {1, 0}, {0, 1}, {1, 1}, {0.5, 0.5}, {0.37, 0.81}};
        StringBuilder sb = new StringBuilder("    \"posed\": {");
        boolean first = true;
        for (HorseSkinGeometry.Skin skin : HorseSkinGeometry.Skin.values()) {
            for (HorseSkinGeometry.Part part : HorseSkinGeometry.Part.values()) {
                if (!HorseSkinGeometry.hasPart(skin, part)) {
                    continue;
                }
                for (HorseSkinGeometry.Face face : HorseSkinGeometry.Face.values()) {
                    sb.append(first ? "\n" : ",\n").append("      \"").append(skin).append('|')
                            .append(part).append('|').append(face).append("\": { \"n\": ")
                            .append(point(HorseSkinGeometry.posedNormal(skin, part, face)))
                            .append(", \"p\": [");
                    for (int i = 0; i < probes.length; i++) {
                        sb.append(i > 0 ? ", " : "").append(point(HorseSkinGeometry.posed(
                                skin, part, face, probes[i][0], probes[i][1])));
                    }
                    sb.append("] }");
                    first = false;
                }
            }
        }
        sb.append("\n    }\n");
        return sb.toString();
    }

    /**
     * A body point, rounded to a precision both languages agree on exactly.
     * Java and JavaScript both use IEEE-754 doubles and both compute this in
     * the same order, so the agreement is real rather than a tolerance - the
     * rounding is only to keep the fixture readable and to stop a negative
     * zero reading as a difference.
     */
    private static String point(HorseSkinGeometry.BodyPoint bp) {
        return "[" + round(bp.x()) + ", " + round(bp.y()) + ", " + round(bp.z()) + "]";
    }

    private static String round(double v) {
        double r = Math.rint(v * 1e6) / 1e6;
        return Double.toString(r == 0.0 ? 0.0 : r);
    }

    private static String hex(int rgb) {
        String h = Integer.toHexString(rgb & 0xFFFFFF);
        return "000000".substring(h.length()) + h;
    }

    /**
     * The effect vocabulary, in the same shape as the mask / op tables above and
     * for the same reason: the creator's effects form is a mirror of
     * {@link AbilityType}, and it omits any parameter left at its default, so a
     * default that drifts writes a gene that plays differently from how it was
     * authored.
     */
    private static String abilityParams(List<AbilityType.Param> ps) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (AbilityType.Param p : ps) {
            sb.append(first ? " " : ", ").append("\"").append(p.name()).append("\": { \"kind\": \"")
                    .append(p.kind()).append("\", \"required\": ")
                    .append(p.fallback() == null && p.kind() != AbilityType.Kind.PARTS);
            Object fallback = p.fallback();
            if (fallback != null && p.kind() != AbilityType.Kind.TRIGGER
                    && p.kind() != AbilityType.Kind.PARTS) {
                sb.append(", \"fallback\": ");
                if (fallback instanceof Number n) {
                    sb.append(num(n.doubleValue()));
                } else if (fallback instanceof Boolean b) {
                    sb.append(b);
                } else {
                    sb.append("\"").append(fallback).append("\"");
                }
            }
            if (!p.choices().isEmpty()) {
                sb.append(", \"choices\": [");
                for (int i = 0; i < p.choices().size(); i++) {
                    sb.append(i > 0 ? ", " : "").append("\"").append(p.choices().get(i)).append("\"");
                }
                sb.append("]");
            }
            sb.append(" }");
            first = false;
        }
        return sb.append(ps.isEmpty() ? "}" : " }").toString();
    }

    private static String params(List<SpecSchema.Param> ps) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (SpecSchema.Param p : ps) {
            sb.append(first ? " " : ", ").append("\"").append(p.name()).append("\": { \"kind\": \"")
                    .append(p.kind()).append("\"");
            if (p.kind() == SpecSchema.Kind.VALUE) {
                sb.append(", \"fallback\": ").append(num(p.fallback()));
            }
            // A flag's default used to be false everywhere, so nothing compared
            // it. The SVG mask has two that default true, and a creator that
            // disagreed about one of those would export a filled shape as a
            // stroked one - silently, and only in the file.
            if (p.kind() == SpecSchema.Kind.FLAG) {
                sb.append(", \"fallback\": ").append(p.fallback() != 0);
            }
            if (!p.choices().isEmpty()) {
                sb.append(", \"choices\": [");
                for (int i = 0; i < p.choices().size(); i++) {
                    sb.append(i > 0 ? ", " : "").append("\"").append(p.choices().get(i)).append("\"");
                }
                sb.append("]");
            }
            sb.append(" }");
            first = false;
        }
        return sb.append(ps.isEmpty() ? "}" : " }").toString();
    }

    private static String bake(SpecGene gene, String file, long seed, int dose, Skin skin) {
        GeneSpec spec = gene.spec();
        // The creator has no horse, so it rolls a founder's values directly.
        // Match that: the same SeededRng, namespaced by gene key exactly as an
        // allele copy's would have been.
        SpecValues values = SpecValues.read(spec,
                EpiRoll.founder(SpecValues.schema(spec), new SeededRng(seed, spec.key())), dose);

        // Which outcome a horse carrying `dose` copies of the first-declared
        // allele lands on. The fixture pins the resolution table as well as the
        // painting, so a creator that maps a combination to the wrong
        // expression fails parity instead of quietly previewing another horse.
        AllelePair pair = pairForDose(gene, dose);
        GeneSpec.ExpressionSpec expressed = gene.expressionSpecOf(pair);

        StringBuilder sb = new StringBuilder();
        sb.append("    { \"spec\": \"").append(file).append("\", \"seed\": ").append(seed)
                .append(", \"dose\": ").append(dose)
                .append(", \"combination\": \"").append(pair.toTokens()).append("\"")
                .append(", \"expression\": \"").append(expressed.id()).append("\"")
                .append(", \"skin\": \"").append(skin).append("\",\n");

        sb.append("      \"knobs\": [");
        for (int i = 0; i < spec.knobs().size(); i++) {
            GeneSpec.Knob knob = spec.knobs().get(i);
            if (i > 0) {
                sb.append(", ");
            }
            if (knob.seed()) {
                sb.append("\"seed\"");
            } else {
                sb.append("[");
                GeneSpec.Value ref = new GeneSpec.Value.FromKnob(i);
                int copies = knob.perLeg() ? SpecValues.LEG_COUNT : 1;
                for (int leg = 0; leg < copies; leg++) {
                    sb.append(leg > 0 ? ", " : "").append(num(values.get(ref, leg)));
                }
                sb.append("]");
            }
        }
        sb.append("],\n");

        CoatBuildContext ctx = new CoatBuildContext(Genotype.wildType(), Epigenome.fromSeed(seed), skin, true);
        PigmentField base = new PigmentField(HorseSkinGeometry.SHEET_SIZE);
        sb.append("      \"probes\": [");
        boolean first = true;
        if (spec.natural()) {
            PigmentField after = SpecPainter.restrict(spec, expressed.layers(), values, ctx, base);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(num(after.red(probe[0], probe[1]))).append(", ")
                        .append(num(after.black(probe[0], probe[1]))).append("]");
            }
        } else {
            ColorField colour = resolvedBlackCoat(skin);
            ColorField delta = SpecPainter.tint(spec, expressed.layers(), values, ctx, base, colour);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(delta.red(probe[0], probe[1])).append(", ")
                        .append(delta.green(probe[0], probe[1])).append(", ")
                        .append(delta.blue(probe[0], probe[1])).append(", ")
                        .append(delta.opacity(probe[0], probe[1])).append("]");
            }
        }
        sb.append("] }");
        return sb.toString();
    }

    /** The combination a horse carrying {@code dose} copies of the first-declared allele holds. */
    private static AllelePair pairForDose(SpecGene gene, int dose) {
        Allele variant = gene.alleles().get(0);
        Allele baseline = gene.defaultAllele();
        return switch (dose) {
            case 2 -> new AllelePair(variant, variant);
            case 1 -> new AllelePair(variant, baseline);
            default -> new AllelePair(baseline, baseline);
        };
    }

    /**
     * A stand-in for "the coat so far" in the magical case: an opaque mid-grey,
     * which is enough for TINT and TOWARD to have something to read and is
     * trivially reproducible on the JavaScript side.
     */
    private static ColorField resolvedBlackCoat(Skin skin) {
        ColorField colour = new ColorField(HorseSkinGeometry.SHEET_SIZE);
        HorseSkinGeometry.forEachTexel(skin, (px, py, part, face, point) ->
                colour.setArgb(px, py, 0xFF404040));
        return colour;
    }

    /** Four probe texels on each of eight parts - enough to localise a mismatch. */
    private static List<int[]> probes(Skin skin) {
        List<int[]> out = new ArrayList<>();
        for (Part part : PROBE_PARTS) {
            if (!HorseSkinGeometry.hasPart(skin, part)) {
                continue;
            }
            List<int[]> found = new ArrayList<>();
            HorseSkinGeometry.forEachTexel(skin, part, (px, py, p, face, point) -> found.add(new int[]{px, py}));
            for (int i = 0; i < 4 && !found.isEmpty(); i++) {
                out.add(found.get((int) ((long) i * (found.size() - 1) / 3)));
            }
        }
        return out;
    }

    /**
     * <b>The {@code PATH} mask's morph, as an answer table</b> - here for the
     * reason {@link #svgSection} spells out, and demonstrated rather than
     * assumed: with a minimal shape on {@code prismatic}'s crescent and nothing
     * else, <b>reversing the blend in the creator's port left the probe cases
     * green</b>. The crescent is a few dozen texels on the flank and the probes
     * sample four per part, so they simply never met.
     *
     * <p>So the blend is compared where it happens: the same control points,
     * the same sample points, at five points along the dial. A port that lerps
     * the wrong way, normalises the dial differently, or morphs the polyline
     * instead of the control points disagrees here on the first row.
     */
    private static String pathSection() {
        // A straight run and a curve, each with a twin it shrinks toward. The
        // curve matters on its own: Catmull-Rom is linear in its control
        // points, so blending them and then splining is the same as splining
        // both and blending - which is what lets the lerp live inside the
        // sampler, and is worth pinning in case either side stops doing it.
        double[] full = {0.1, 0.5, 0.9, 0.5};
        double[] fullMin = {0.4, 0.5, 0.6, 0.5};
        double[] curve = {0.1, 0.4, 0.35, 0.8, 0.65, 0.2, 0.9, 0.6};
        double[] curveMin = {0.4, 0.45, 0.47, 0.6, 0.55, 0.4, 0.6, 0.55};
        double[][] probes = {{0.5, 0.5}, {0.3, 0.5}, {0.85, 0.5}, {0.2, 0.45}, {0.7, 0.62}};
        double[] dials = {0.0, 0.25, 0.5, 0.75, 1.0};

        StringBuilder sb = new StringBuilder("    \"path\": {\n      \"curveSamples\": ")
                .append(SpecSchema.PATH_CURVE_SAMPLES)
                .append(",\n      \"maxPoints\": ").append(SpecSchema.MAX_PATH_POINTS)
                .append(",\n      \"probes\": [");
        for (int i = 0; i < probes.length; i++) {
            sb.append(i > 0 ? ", " : "").append("[").append(num(probes[i][0])).append(", ")
                    .append(num(probes[i][1])).append("]");
        }
        sb.append("],\n      \"dials\": [");
        for (int i = 0; i < dials.length; i++) {
            sb.append(i > 0 ? ", " : "").append(num(dials[i]));
        }
        sb.append("],\n      \"cases\": {");
        sb.append(pathCase("straight", full, fullMin, false, false, probes, dials));
        sb.append(",").append(pathCase("curved", curve, curveMin, true, false, probes, dials));
        sb.append(",").append(pathCase("filled", curve, curveMin, true, true, probes, dials));
        // And one with no minimal shape at all: the dial must then be ignored
        // entirely rather than quietly scaling the shape toward nothing.
        sb.append(",").append(pathCase("noMinimum", curve, null, true, false, probes, dials));
        sb.append("\n      }\n    },\n");
        return sb.toString();
    }

    private static String pathCase(String name, double[] pts, double[] min, boolean curve,
                                   boolean fill, double[][] probes, double[] dials) {
        StringBuilder sb = new StringBuilder("\n        \"").append(name).append("\": { \"points\": [");
        for (int i = 0; i < pts.length; i++) {
            sb.append(i > 0 ? ", " : "").append(num(pts[i]));
        }
        sb.append("], \"pointsMin\": ");
        if (min == null) {
            sb.append("null");
        } else {
            sb.append("[");
            for (int i = 0; i < min.length; i++) {
                sb.append(i > 0 ? ", " : "").append(num(min[i]));
            }
            sb.append("]");
        }
        sb.append(", \"curve\": ").append(curve).append(", \"fill\": ").append(fill)
                .append(", \"coverage\": [");
        boolean first = true;
        for (double dial : dials) {
            for (double[] probe : probes) {
                sb.append(first ? "" : ", ").append(num(SpecPainter.pathCoverage(
                        pts, min, dial, curve, fill, fill,
                        0, 1, 0, 1, probe[0], probe[1], 0.06, 0.05)));
                first = false;
            }
        }
        sb.append("] }");
        return sb.toString();
    }

    /**
     * <b>The SVG mask's geometry, as answer tables</b> - the same shape as
     * {@link #composerSection}, and for the same reason.
     *
     * <p>The probe cases sample four texels per part. A drawing placed on the
     * flank is a few dozen texels; the chance those two sets intersect is not
     * something to rest a port on, and a mask that is never reached makes the
     * parity check <i>green by definition</i> about it - which is exactly the
     * failure {@code expected.json} being stale once caused, in the other
     * direction.
     *
     * <p>So the path grammar is compared directly: parse a handful of strings
     * that each exercise one thing that is easy to get subtly wrong, and record
     * the point count, the bounds, the fill rule's answers, the distance under
     * each cap, and the transform and fit arithmetic. If the two parsers
     * disagree about any of it, they disagree here rather than on a horse
     * somebody is looking at.
     */
    /** A JSON string. The cases below carry no quote and no backslash, and must not. */
    private static String quote(String s) {
        return "\"" + s + "\"";
    }

    private static String svgSection() {
        String[][] paths = {
                // absolute, relative, shorthand, and a moveto's repeated pairs
                {"square", "M 0 0 L 10 0 L 10 10 L 0 10 Z", ""},
                {"relative", "m 0 0 l 10 0 l 0 10 l -10 0 z", ""},
                {"shorthand", "M 0 0 H 10 V 10 H 0 Z", ""},
                // the number grammar: a run-on minus, a run-on dot, an exponent
                {"runOnNumbers", "M0 0L10-5L1e1 5Z", ""},
                {"dottedNumbers", "M.5.5L2.5.5L2.5 3Z", ""},
                // the reflected control points
                {"smoothCubic", "M 0 0 C 5 -8 15 -8 20 0 S 35 8 40 0", ""},
                {"smoothQuad", "M 0 0 Q 10 -12 20 0 T 40 0", ""},
                // the arc, both sweeps and a large-arc, plus a radius correction
                {"arcs", "M 0 0 A 10 10 0 0 1 20 0 A 6 6 0 1 0 20 12 A 1 1 0 0 1 0 12 Z", ""},
                // subpaths and a hole
                {"hole", "M 0 0 H 30 V 30 H 0 Z M 10 10 H 20 V 20 H 10 Z", ""},
                // a closepath with no moveto after it
                {"chained", "M 0 0 H 10 V 10 Z L -10 0 L -10 10 Z", ""},
                // and the transform list, composed left to right
                {"transformed", "M 0 0 H 5 V 5", "translate(10 4) rotate(30 2 2) scale(2 1.5)"}
        };
        double[][] probes = {{5, 5}, {15, 5}, {-3, 5}, {12, 12}, {0.5, 0.5}, {22, 3}, {8, 24}};
        String[] caps = {"round", "butt", "square"};

        StringBuilder sb = new StringBuilder("    \"svg\": {\n      \"maxPoints\": ")
                .append(SvgPath.MAX_POINTS)
                .append(",\n      \"curveSamples\": ").append(SvgPath.CURVE_SAMPLES)
                .append(",\n      \"arcSamplesPerTurn\": ").append(SvgPath.ARC_SAMPLES_PER_TURN)
                .append(",\n      \"paths\": {");
        double[] hit = new double[3];
        for (int i = 0; i < paths.length; i++) {
            SvgPath.Shape shape = SvgPath.parse(paths[i][1], paths[i][2].isEmpty() ? null : paths[i][2]);
            sb.append(i > 0 ? "," : "").append("\n        \"").append(paths[i][0]).append("\": { \"d\": ")
                    .append(quote(paths[i][1]));
            if (!paths[i][2].isEmpty()) {
                sb.append(", \"transform\": ").append(quote(paths[i][2]));
            }
            sb.append(", \"points\": ").append(shape.xs().length)
                    .append(", \"subpaths\": ").append(shape.subpaths())
                    .append(", \"box\": [").append(num(shape.box()[0])).append(", ")
                    .append(num(shape.box()[1])).append(", ").append(num(shape.box()[2]))
                    .append(", ").append(num(shape.box()[3])).append("]");
            sb.append(", \"length\": ").append(num(shape.cum()[shape.cum().length - 1]));
            sb.append(", \"nonzero\": [");
            for (int k = 0; k < probes.length; k++) {
                sb.append(k > 0 ? ", " : "").append(SvgPath.inside(shape, probes[k][0], probes[k][1], false));
            }
            sb.append("], \"evenodd\": [");
            for (int k = 0; k < probes.length; k++) {
                sb.append(k > 0 ? ", " : "").append(SvgPath.inside(shape, probes[k][0], probes[k][1], true));
            }
            sb.append("]");
            for (String cap : caps) {
                sb.append(", \"").append(cap).append("\": [");
                for (int k = 0; k < probes.length; k++) {
                    SvgPath.distance(shape, probes[k][0], probes[k][1], cap, 0.5, hit);
                    sb.append(k > 0 ? ", " : "").append(num(hit[0])).append(", ").append(num(hit[1]));
                }
                sb.append("]");
            }
            sb.append(", \"miter\": [");
            for (int k = 0; k < probes.length; k++) {
                double d = SvgPath.miterDistance(shape, probes[k][0], probes[k][1], 0.5, 4.0);
                sb.append(k > 0 ? ", " : "").append(num(Math.min(d, 99)));
            }
            sb.append("] }");
        }
        sb.append("\n      },\n      \"probes\": [");
        for (int k = 0; k < probes.length; k++) {
            sb.append(k > 0 ? ", " : "").append("[").append(num(probes[k][0])).append(", ")
                    .append(num(probes[k][1])).append("]");
        }
        sb.append("],\n      \"fits\": {");
        String[] modes = {"meet", "slice", "none"};
        String[] aligns = {"xMidYMid", "xMinYMin", "xMaxYMax"};
        double[] viewBox = {-10, 5, 100, 50};
        boolean firstFit = true;
        for (String mode : modes) {
            for (String align : aligns) {
                double[] f = SvgPath.fit(viewBox, 3, 7, 40, 20, mode, align);
                sb.append(firstFit ? "" : ",").append("\n        \"").append(mode).append(" ").append(align)
                        .append("\": [").append(num(f[0])).append(", ").append(num(f[1])).append(", ")
                        .append(num(f[2])).append(", ").append(num(f[3])).append("]");
                firstFit = false;
            }
        }
        sb.append("\n      },\n      \"viewBox\": [").append(num(viewBox[0])).append(", ")
                .append(num(viewBox[1])).append(", ").append(num(viewBox[2])).append(", ")
                .append(num(viewBox[3])).append("]\n    },\n");
        return sb.toString();
    }

    private static String num(double v) {
        return String.format(Locale.ROOT, "%.6f", v);
    }

    private static String read(String file) {
        String resource = "/horsegenetics/example-genes/" + file;
        try (InputStream in = SpecFixtureTool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("missing " + resource);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }
}
