package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.SeededRng;
import com.example.horsegenetics.common.coat.pattern.CoatBuildContext;
import com.example.horsegenetics.common.coat.pattern.ColorField;
import com.example.horsegenetics.common.coat.pattern.PigmentField;
import com.example.horsegenetics.common.coat.pattern.SpecPainter;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Part;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Skin;
import com.example.horsegenetics.common.genetics.Allele;
import com.example.horsegenetics.common.genetics.AllelePair;
import com.example.horsegenetics.common.genetics.Epigenome;
import com.example.horsegenetics.common.genetics.Genotype;
import com.example.horsegenetics.common.genetics.epi.EpiRoll;

import java.io.IOException;
import com.example.horsegenetics.common.coat.pattern.CoatTextureComposer;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Writes the <b>parity fixtures</b> the gene creator checks itself against.
 *
 * <p>The creator previews a gene by running a JavaScript twin of
 * {@link SpecPainter}. A twin can drift, and a drifted twin is worse than no
 * preview at all - it shows a horse the game will not breed, convincingly. So
 * this tool bakes a set of example genes through the <b>real</b> Java engine and
 * records what it got; {@code wiki/gene-creator/tools/check-parity.mjs} runs the
 * same specs through the JavaScript and compares.
 *
 * <p>What it records per case: every knob the horse drew (which checks the
 * {@code java.util.Random} port as much as the painter), and the pigment or
 * colour at a spread of probe texels. Probes rather than a whole-sheet hash
 * because a mismatch should say <i>which texel on which part</i>, not just
 * "different".
 *
 * <p>{@code ./gradlew :common:bakeSpecFixtures}
 */
public final class SpecFixtureTool {

    /** Example genes to bake, from {@code main/resources/horsegenetics/example-genes/}. */
    private static final String[] SPECS = {"silver.json", "dun.json", "tobiano.json", "aurora.json", "prismatic.json"};

    /** Preview seeds - the same numbers the creator's seed box defaults to. */
    private static final long[] SEEDS = {1L, 7L, 21L};

    private static final Part[] PROBE_PARTS = {
            Part.BODY, Part.NECK, Part.HEAD, Part.MANE, Part.TAIL,
            Part.LEFT_FRONT_LEG, Part.RIGHT_HIND_LEG, Part.LEFT_EAR
    };

    private SpecFixtureTool() {}

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "wiki/gene-creator/fixtures/expected.json");
        Files.createDirectories(out.getParent());

        StringBuilder json = new StringBuilder();
        json.append("{\n  \"note\": \"GENERATED by :common:bakeSpecFixtures - do not hand-edit.\",\n");
        json.append(schemaSection());
        json.append("  \"cases\": [\n");

        List<String> cases = new ArrayList<>();
        for (String file : SPECS) {
            GeneSpec spec = GeneSpecParser.parse(read(file), file);
            SpecGene gene = new SpecGene(spec);
            for (long seed : SEEDS) {
                for (int dose : new int[]{1, 2}) {
                    for (Skin skin : Skin.values()) {
                        cases.add(bake(gene, file, seed, dose, skin));
                    }
                }
            }
        }
        json.append(String.join(",\n", cases));
        json.append("\n  ]\n}\n");
        Files.writeString(out, json.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + cases.size() + " parity cases to " + out.toAbsolutePath());

        // The same fixtures again as a classic script, so the creator can run
        // the parity check on itself when it boots. It cannot read the .json:
        // under file:// a fetch of a sibling file is blocked, which is the same
        // reason the textures and the examples are inlined.
        Path script = out.resolveSibling("expected.js");
        Files.writeString(script, """
                // GENERATED by :common:bakeSpecFixtures - do not hand-edit.
                // The twin of expected.json, as a classic script: the creator runs
                // js/parity.js against this on boot, and a file:// page cannot fetch
                // the .json sitting next to it.
                window.HG = window.HG || {};
                window.HG.fixtures =\s""" + json.toString().stripTrailing() + ";\n",
                StandardCharsets.UTF_8);
        System.out.println("wrote " + script.toAbsolutePath());
    }

    /**
     * The schema's defaults, so the creator can prove its mirror still matches.
     * This is not paranoia: the creator omits any setting equal to its default,
     * so a default that differs between the two writes a file that plays
     * differently from how it previewed - silently, and only for the settings
     * you left alone.
     */
    private static String schemaSection() {
        StringBuilder sb = new StringBuilder("  \"schema\": {\n    \"masks\": {");
        boolean first = true;
        for (GeneSpec.MaskType type : GeneSpec.MaskType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": ")
                    .append(params(SpecSchema.maskParams(type)));
            first = false;
        }
        sb.append("\n    },\n    \"ops\": {");
        first = true;
        for (GeneSpec.OpType type : GeneSpec.OpType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": { \"phase\": \"")
                    .append(type.isNatural() ? "natural" : "magical").append("\", \"params\": ")
                    .append(params(SpecSchema.opParams(type))).append(" }");
            first = false;
        }
        sb.append("\n    },\n    \"effects\": {");
        first = true;
        for (AbilityType type : AbilityType.all()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type.name()).append("\": ")
                    .append(abilityParams(type.params()));
            first = false;
        }
        sb.append("\n    },\n    \"conditionFlags\": [");
        for (int i = 0; i < AbilityType.CONDITION_FLAGS.size(); i++) {
            sb.append(i > 0 ? ", " : "").append("\"").append(AbilityType.CONDITION_FLAGS.get(i)).append("\"");
        }
        sb.append("],\n");
        // A shared CONSTANT rather than a schema parameter, and so invisible to
        // the parameter comparison above. It still has to match, and the probe
        // cases cannot be relied on to notice: they sample four texels per part,
        // and one sub-segment more or less on a curve moves the line by a
        // fraction of a texel. Compared directly, like the condition flags.
        sb.append("    \"pathCurveSamples\": ").append(SpecSchema.PATH_CURVE_SAMPLES)
                .append(",\n");
        sb.append(composerSection());
        sb.append(geometrySection());
        sb.append("  },\n");
        return sb.toString();
    }

    /**
     * The <b>composer's arithmetic</b>, as answer tables.
     *
     * <p>{@code check-parity.mjs} runs {@code restrict} and {@code tint} and
     * never runs {@code compose}, so everything in the creator's composite
     * mirror - the phase-2 alpha ramp, the phase-3a shadow lift, the final
     * multiply - had never been compared against anything. That is the hole
     * known-gaps gap 50 lived in: the mirror kept an {@code rgb == 0} equality
     * for months after the game replaced it with a ramp, the equality stopped
     * matching anything at all when the gradient's black corner moved off
     * {@code #000000}, and the creator quietly drew every dark coat at full
     * opacity.
     *
     * <p>The composite itself is not comparable here - it needs the gradient
     * and the template, and the Node harness has no image decoder. The
     * arithmetic is, because both functions are pure functions of ints, and the
     * arithmetic is where the drift was. The inputs below are chosen to sit on
     * both sides of every threshold: pure black, the shipped chart's actual
     * black, either side of NEAR_BLACK, and an ordinary coat colour.
     */
    private static String composerSection() {
        int[] probes = {0x000000, 0x0C0C0C, 0x161515, 0x2F2F2F, 0x303030, 0x9B4A28, 0xFFFFFF};
        StringBuilder sb = new StringBuilder("    \"composer\": {\n      \"nearBlackAlpha\": {");
        for (int i = 0; i < probes.length; i++) {
            sb.append(i > 0 ? ", " : " ").append("\"").append(hex(probes[i])).append("\": ")
                    .append(CoatTextureComposer.nearBlackAlphaFor(probes[i]));
        }
        sb.append(" },\n      \"shadowFloor\": ").append(CoatTextureComposer.shadowFloor());
        sb.append(",\n      \"liftShadows\": {");
        for (int i = 0; i < probes.length; i++) {
            int lifted = CoatTextureComposer.liftedForParity(probes[i]);
            sb.append(i > 0 ? ", " : " ").append("\"").append(hex(probes[i])).append("\": \"")
                    .append(hex(lifted)).append("\"");
        }
        sb.append(" }\n    },\n");
        return sb.toString();
    }

    /**
     * The <b>posed mesh</b>, as an answer table.
     *
     * <p>This is what closes known-gaps gap 100. {@code HorseSkinGeometry.posed} and
     * {@code posedNormal} walk the raw cuboid rather than its bounding box,
     * and the browser needs the same walk to draw a horse whose neck is
     * pitched. For a while that arithmetic existed <b>twice</b> - here, and
     * again in the creator's {@code model3d.js} - in two languages, in two
     * files that were not obviously a pair, with nothing comparing them. A
     * change to how a part is posed could reach the baked icons and not the
     * browser preview, or the reverse, and the symptom would be a wiki quietly
     * drawing a slightly different horse from the one the game breeds.
     *
     * <p>The creator's copy now lives in {@code geometry.js}, beside the rest
     * of its port of this class, and this table is what holds the two
     * together.
     *
     * <p><b>Corners alone would not do it.</b> A corner is a fraction of 0 or
     * 1 on both axes, and several ways of getting the axis pairing wrong agree
     * at the corners and disagree everywhere else - which is the exact shape of
     * the UV swap that once hid behind a stale fixture. So the probes include
     * both face centres and an off-centre point with no symmetry to it, and
     * they cover every part of both skins: a baby horse is not a scaled adult.
     */
    private static String geometrySection() {
        double[][] probes = {{0, 0}, {1, 0}, {0, 1}, {1, 1}, {0.5, 0.5}, {0.37, 0.81}};
        StringBuilder sb = new StringBuilder("    \"posed\": {");
        boolean first = true;
        for (HorseSkinGeometry.Skin skin : HorseSkinGeometry.Skin.values()) {
            for (HorseSkinGeometry.Part part : HorseSkinGeometry.Part.values()) {
                if (!HorseSkinGeometry.hasPart(skin, part)) {
                    continue;
                }
                for (HorseSkinGeometry.Face face : HorseSkinGeometry.Face.values()) {
                    sb.append(first ? "\n" : ",\n").append("      \"").append(skin).append('|')
                            .append(part).append('|').append(face).append("\": { \"n\": ")
                            .append(point(HorseSkinGeometry.posedNormal(skin, part, face)))
                            .append(", \"p\": [");
                    for (int i = 0; i < probes.length; i++) {
                        sb.append(i > 0 ? ", " : "").append(point(HorseSkinGeometry.posed(
                                skin, part, face, probes[i][0], probes[i][1])));
                    }
                    sb.append("] }");
                    first = false;
                }
            }
        }
        sb.append("\n    }\n");
        return sb.toString();
    }

    /**
     * A body point, rounded to a precision both languages agree on exactly.
     * Java and JavaScript both use IEEE-754 doubles and both compute this in
     * the same order, so the agreement is real rather than a tolerance - the
     * rounding is only to keep the fixture readable and to stop a negative
     * zero reading as a difference.
     */
    private static String point(HorseSkinGeometry.BodyPoint bp) {
        return "[" + round(bp.x()) + ", " + round(bp.y()) + ", " + round(bp.z()) + "]";
    }

    private static String round(double v) {
        double r = Math.rint(v * 1e6) / 1e6;
        return Double.toString(r == 0.0 ? 0.0 : r);
    }

    private static String hex(int rgb) {
        String h = Integer.toHexString(rgb & 0xFFFFFF);
        return "000000".substring(h.length()) + h;
    }

    /**
     * The effect vocabulary, in the same shape as the mask / op tables above and
     * for the same reason: the creator's effects form is a mirror of
     * {@link AbilityType}, and it omits any parameter left at its default, so a
     * default that drifts writes a gene that plays differently from how it was
     * authored.
     */
    private static String abilityParams(List<AbilityType.Param> ps) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (AbilityType.Param p : ps) {
            sb.append(first ? " " : ", ").append("\"").append(p.name()).append("\": { \"kind\": \"")
                    .append(p.kind()).append("\", \"required\": ")
                    .append(p.fallback() == null && p.kind() != AbilityType.Kind.PARTS);
            Object fallback = p.fallback();
            if (fallback != null && p.kind() != AbilityType.Kind.TRIGGER
                    && p.kind() != AbilityType.Kind.PARTS) {
                sb.append(", \"fallback\": ");
                if (fallback instanceof Number n) {
                    sb.append(num(n.doubleValue()));
                } else if (fallback instanceof Boolean b) {
                    sb.append(b);
                } else {
                    sb.append("\"").append(fallback).append("\"");
                }
            }
            if (!p.choices().isEmpty()) {
                sb.append(", \"choices\": [");
                for (int i = 0; i < p.choices().size(); i++) {
                    sb.append(i > 0 ? ", " : "").append("\"").append(p.choices().get(i)).append("\"");
                }
                sb.append("]");
            }
            sb.append(" }");
            first = false;
        }
        return sb.append(ps.isEmpty() ? "}" : " }").toString();
    }

    private static String params(List<SpecSchema.Param> ps) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (SpecSchema.Param p : ps) {
            sb.append(first ? " " : ", ").append("\"").append(p.name()).append("\": { \"kind\": \"")
                    .append(p.kind()).append("\"");
            if (p.kind() == SpecSchema.Kind.VALUE) {
                sb.append(", \"fallback\": ").append(num(p.fallback()));
            }
            if (!p.choices().isEmpty()) {
                sb.append(", \"choices\": [");
                for (int i = 0; i < p.choices().size(); i++) {
                    sb.append(i > 0 ? ", " : "").append("\"").append(p.choices().get(i)).append("\"");
                }
                sb.append("]");
            }
            sb.append(" }");
            first = false;
        }
        return sb.append(ps.isEmpty() ? "}" : " }").toString();
    }

    private static String bake(SpecGene gene, String file, long seed, int dose, Skin skin) {
        GeneSpec spec = gene.spec();
        // The creator has no horse, so it rolls a founder's values directly.
        // Match that: the same SeededRng, namespaced by gene key exactly as an
        // allele copy's would have been.
        SpecValues values = SpecValues.read(spec,
                EpiRoll.founder(SpecValues.schema(spec), new SeededRng(seed, spec.key())), dose);

        // Which outcome a horse carrying `dose` copies of the first-declared
        // allele lands on. The fixture pins the resolution table as well as the
        // painting, so a creator that maps a combination to the wrong
        // expression fails parity instead of quietly previewing another horse.
        AllelePair pair = pairForDose(gene, dose);
        GeneSpec.ExpressionSpec expressed = gene.expressionSpecOf(pair);

        StringBuilder sb = new StringBuilder();
        sb.append("    { \"spec\": \"").append(file).append("\", \"seed\": ").append(seed)
                .append(", \"dose\": ").append(dose)
                .append(", \"combination\": \"").append(pair.toTokens()).append("\"")
                .append(", \"expression\": \"").append(expressed.id()).append("\"")
                .append(", \"skin\": \"").append(skin).append("\",\n");

        sb.append("      \"knobs\": [");
        for (int i = 0; i < spec.knobs().size(); i++) {
            GeneSpec.Knob knob = spec.knobs().get(i);
            if (i > 0) {
                sb.append(", ");
            }
            if (knob.seed()) {
                sb.append("\"seed\"");
            } else {
                sb.append("[");
                GeneSpec.Value ref = new GeneSpec.Value.FromKnob(i);
                int copies = knob.perLeg() ? SpecValues.LEG_COUNT : 1;
                for (int leg = 0; leg < copies; leg++) {
                    sb.append(leg > 0 ? ", " : "").append(num(values.get(ref, leg)));
                }
                sb.append("]");
            }
        }
        sb.append("],\n");

        CoatBuildContext ctx = new CoatBuildContext(Genotype.wildType(), Epigenome.fromSeed(seed), skin, true);
        PigmentField base = new PigmentField(HorseSkinGeometry.SHEET_SIZE);
        sb.append("      \"probes\": [");
        boolean first = true;
        if (spec.natural()) {
            PigmentField after = SpecPainter.restrict(spec, expressed.layers(), values, ctx, base);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(num(after.red(probe[0], probe[1]))).append(", ")
                        .append(num(after.black(probe[0], probe[1]))).append("]");
            }
        } else {
            ColorField colour = resolvedBlackCoat(skin);
            ColorField delta = SpecPainter.tint(spec, expressed.layers(), values, ctx, base, colour);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(delta.red(probe[0], probe[1])).append(", ")
                        .append(delta.green(probe[0], probe[1])).append(", ")
                        .append(delta.blue(probe[0], probe[1])).append(", ")
                        .append(delta.opacity(probe[0], probe[1])).append("]");
            }
        }
        sb.append("] }");
        return sb.toString();
    }

    /** The combination a horse carrying {@code dose} copies of the first-declared allele holds. */
    private static AllelePair pairForDose(SpecGene gene, int dose) {
        Allele variant = gene.alleles().get(0);
        Allele baseline = gene.defaultAllele();
        return switch (dose) {
            case 2 -> new AllelePair(variant, variant);
            case 1 -> new AllelePair(variant, baseline);
            default -> new AllelePair(baseline, baseline);
        };
    }

    /**
     * A stand-in for "the coat so far" in the magical case: an opaque mid-grey,
     * which is enough for TINT and TOWARD to have something to read and is
     * trivially reproducible on the JavaScript side.
     */
    private static ColorField resolvedBlackCoat(Skin skin) {
        ColorField colour = new ColorField(HorseSkinGeometry.SHEET_SIZE);
        HorseSkinGeometry.forEachTexel(skin, (px, py, part, face, point) ->
                colour.setArgb(px, py, 0xFF404040));
        return colour;
    }

    /** Four probe texels on each of eight parts - enough to localise a mismatch. */
    private static List<int[]> probes(Skin skin) {
        List<int[]> out = new ArrayList<>();
        for (Part part : PROBE_PARTS) {
            if (!HorseSkinGeometry.hasPart(skin, part)) {
                continue;
            }
            List<int[]> found = new ArrayList<>();
            HorseSkinGeometry.forEachTexel(skin, part, (px, py, p, face, point) -> found.add(new int[]{px, py}));
            for (int i = 0; i < 4 && !found.isEmpty(); i++) {
                out.add(found.get((int) ((long) i * (found.size() - 1) / 3)));
            }
        }
        return out;
    }

    private static String num(double v) {
        return String.format(Locale.ROOT, "%.6f", v);
    }

    private static String read(String file) {
        String resource = "/horsegenetics/example-genes/" + file;
        try (InputStream in = SpecFixtureTool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("missing " + resource);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }
}
