package com.example.horsegenetics.common.genetics.spec;

import com.example.horsegenetics.common.SeededRng;
import com.example.horsegenetics.common.coat.pattern.CoatBuildContext;
import com.example.horsegenetics.common.coat.pattern.ColorField;
import com.example.horsegenetics.common.coat.pattern.PigmentField;
import com.example.horsegenetics.common.coat.pattern.SpecPainter;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Part;
import com.example.horsegenetics.common.coat.skin.HorseSkinGeometry.Skin;
import com.example.horsegenetics.common.genetics.Epigenome;
import com.example.horsegenetics.common.genetics.Genotype;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Writes the <b>parity fixtures</b> the gene creator checks itself against.
 *
 * <p>The creator previews a gene by running a JavaScript twin of
 * {@link SpecPainter}. A twin can drift, and a drifted twin is worse than no
 * preview at all - it shows a horse the game will not breed, convincingly. So
 * this tool bakes a set of example genes through the <b>real</b> Java engine and
 * records what it got; {@code wiki/gene-creator/tools/check-parity.mjs} runs the
 * same specs through the JavaScript and compares.
 *
 * <p>What it records per case: every knob the horse drew (which checks the
 * {@code java.util.Random} port as much as the painter), and the pigment or
 * colour at a spread of probe texels. Probes rather than a whole-sheet hash
 * because a mismatch should say <i>which texel on which part</i>, not just
 * "different".
 *
 * <p>{@code ./gradlew :common:bakeSpecFixtures}
 */
public final class SpecFixtureTool {

    /** Example genes to bake, from {@code main/resources/horsegenetics/example-genes/}. */
    private static final String[] SPECS = {"silver.json", "dun.json", "tobiano.json", "aurora.json"};

    /** Preview seeds - the same numbers the creator's seed box defaults to. */
    private static final long[] SEEDS = {1L, 7L, 21L};

    private static final Part[] PROBE_PARTS = {
            Part.BODY, Part.NECK, Part.HEAD, Part.MANE, Part.TAIL,
            Part.LEFT_FRONT_LEG, Part.RIGHT_HIND_LEG, Part.LEFT_EAR
    };

    private SpecFixtureTool() {}

    public static void main(String[] args) throws IOException {
        Path out = Path.of(args.length > 0 ? args[0] : "wiki/gene-creator/fixtures/expected.json");
        Files.createDirectories(out.getParent());

        StringBuilder json = new StringBuilder();
        json.append("{\n  \"note\": \"GENERATED by :common:bakeSpecFixtures - do not hand-edit.\",\n");
        json.append(schemaSection());
        json.append("  \"cases\": [\n");

        List<String> cases = new ArrayList<>();
        for (String file : SPECS) {
            GeneSpec spec = GeneSpecParser.parse(read(file), file);
            SpecGene gene = new SpecGene(spec);
            for (long seed : SEEDS) {
                for (int dose : new int[]{1, 2}) {
                    for (Skin skin : Skin.values()) {
                        cases.add(bake(gene, file, seed, dose, skin));
                    }
                }
            }
        }
        json.append(String.join(",\n", cases));
        json.append("\n  ]\n}\n");
        Files.writeString(out, json.toString(), StandardCharsets.UTF_8);
        System.out.println("wrote " + cases.size() + " parity cases to " + out.toAbsolutePath());
    }

    /**
     * The schema's defaults, so the creator can prove its mirror still matches.
     * This is not paranoia: the creator omits any setting equal to its default,
     * so a default that differs between the two writes a file that plays
     * differently from how it previewed - silently, and only for the settings
     * you left alone.
     */
    private static String schemaSection() {
        StringBuilder sb = new StringBuilder("  \"schema\": {\n    \"masks\": {");
        boolean first = true;
        for (GeneSpec.MaskType type : GeneSpec.MaskType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": ")
                    .append(params(SpecSchema.maskParams(type)));
            first = false;
        }
        sb.append("\n    },\n    \"ops\": {");
        first = true;
        for (GeneSpec.OpType type : GeneSpec.OpType.values()) {
            sb.append(first ? "" : ",").append("\n      \"").append(type).append("\": { \"phase\": \"")
                    .append(type.isNatural() ? "natural" : "magical").append("\", \"params\": ")
                    .append(params(SpecSchema.opParams(type))).append(" }");
            first = false;
        }
        sb.append("\n    }\n  },\n");
        return sb.toString();
    }

    private static String params(List<SpecSchema.Param> ps) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (SpecSchema.Param p : ps) {
            sb.append(first ? " " : ", ").append("\"").append(p.name()).append("\": { \"kind\": \"")
                    .append(p.kind()).append("\"");
            if (p.kind() == SpecSchema.Kind.VALUE) {
                sb.append(", \"fallback\": ").append(num(p.fallback()));
            }
            if (!p.choices().isEmpty()) {
                sb.append(", \"choices\": [");
                for (int i = 0; i < p.choices().size(); i++) {
                    sb.append(i > 0 ? ", " : "").append("\"").append(p.choices().get(i)).append("\"");
                }
                sb.append("]");
            }
            sb.append(" }");
            first = false;
        }
        return sb.append(ps.isEmpty() ? "}" : " }").toString();
    }

    private static String bake(SpecGene gene, String file, long seed, int dose, Skin skin) {
        GeneSpec spec = gene.spec();
        // The creator has no horse, so it seeds the draw directly. Match that:
        // the same SeededRng, namespaced by gene key exactly as
        // CoatBuildContext.epigeneticsFor does.
        SpecValues values = SpecValues.draw(spec, new SeededRng(seed, spec.key()), dose);

        StringBuilder sb = new StringBuilder();
        sb.append("    { \"spec\": \"").append(file).append("\", \"seed\": ").append(seed)
                .append(", \"dose\": ").append(dose)
                .append(", \"skin\": \"").append(skin).append("\",\n");

        sb.append("      \"knobs\": [");
        for (int i = 0; i < spec.knobs().size(); i++) {
            GeneSpec.Knob knob = spec.knobs().get(i);
            if (i > 0) {
                sb.append(", ");
            }
            if (knob.seed()) {
                sb.append("\"seed\"");
            } else {
                sb.append("[");
                GeneSpec.Value ref = new GeneSpec.Value.FromKnob(i);
                int copies = knob.perLeg() ? SpecValues.LEG_COUNT : 1;
                for (int leg = 0; leg < copies; leg++) {
                    sb.append(leg > 0 ? ", " : "").append(num(values.get(ref, leg)));
                }
                sb.append("]");
            }
        }
        sb.append("],\n");

        CoatBuildContext ctx = new CoatBuildContext(Genotype.wildType(), Epigenome.fromSeed(seed), skin, true);
        PigmentField base = new PigmentField(HorseSkinGeometry.SHEET_SIZE);
        sb.append("      \"probes\": [");
        boolean first = true;
        if (spec.natural()) {
            PigmentField after = SpecPainter.restrict(spec, values, ctx, base);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(num(after.red(probe[0], probe[1]))).append(", ")
                        .append(num(after.black(probe[0], probe[1]))).append("]");
            }
        } else {
            ColorField colour = resolvedBlackCoat(skin);
            ColorField delta = SpecPainter.tint(spec, values, ctx, base, colour);
            for (int[] probe : probes(skin)) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append("[").append(probe[0]).append(", ").append(probe[1]).append(", ")
                        .append(delta.red(probe[0], probe[1])).append(", ")
                        .append(delta.green(probe[0], probe[1])).append(", ")
                        .append(delta.blue(probe[0], probe[1])).append(", ")
                        .append(delta.opacity(probe[0], probe[1])).append("]");
            }
        }
        sb.append("] }");
        return sb.toString();
    }

    /**
     * A stand-in for "the coat so far" in the magical case: an opaque mid-grey,
     * which is enough for TINT and TOWARD to have something to read and is
     * trivially reproducible on the JavaScript side.
     */
    private static ColorField resolvedBlackCoat(Skin skin) {
        ColorField colour = new ColorField(HorseSkinGeometry.SHEET_SIZE);
        HorseSkinGeometry.forEachTexel(skin, (px, py, part, face, point) ->
                colour.setArgb(px, py, 0xFF404040));
        return colour;
    }

    /** Four probe texels on each of eight parts - enough to localise a mismatch. */
    private static List<int[]> probes(Skin skin) {
        List<int[]> out = new ArrayList<>();
        for (Part part : PROBE_PARTS) {
            if (!HorseSkinGeometry.hasPart(skin, part)) {
                continue;
            }
            List<int[]> found = new ArrayList<>();
            HorseSkinGeometry.forEachTexel(skin, part, (px, py, p, face, point) -> found.add(new int[]{px, py}));
            for (int i = 0; i < 4 && !found.isEmpty(); i++) {
                out.add(found.get((int) ((long) i * (found.size() - 1) / 3)));
            }
        }
        return out;
    }

    private static String num(double v) {
        return String.format(Locale.ROOT, "%.6f", v);
    }

    private static String read(String file) {
        String resource = "/horsegenetics/example-genes/" + file;
        try (InputStream in = SpecFixtureTool.class.getResourceAsStream(resource)) {
            if (in == null) {
                throw new IllegalStateException("missing " + resource);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }
}
