package com.example.horsegenetics.common.genetics.spec;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * <b>Which genes nobody has confirmed by eye, worst-first</b> - baked to a
 * classpath resource so the game can read an answer that only the wiki knows.
 *
 * <pre>./gradlew :common:bakeUnverifiedGenes</pre>
 *
 * <h2>Why this is baked rather than asked at runtime</h2>
 * The wiki is not in the jar, and it never will be: it is the documentation, not
 * the mod. But the fact the horse dimension needs - <i>has anybody actually
 * looked at this gene in the game?</i> - is recorded there and nowhere else, by
 * hard rule 9: a thing that is verified is deleted from
 * {@code wiki/verification.html} and written up under {@code <h3 id="verified">}
 * on its own page's coding tab. So this walks the pages at build time and writes
 * the answer where {@code CoatCheckPlan} can read it.
 *
 * <p>Writing a <b>second hand-kept list</b> of what is unverified was the
 * alternative and it is the one thing this project keeps proving does not work:
 * the list drifts, and a drifted list of what to test is worse than none,
 * because it says "done" about something nobody looked at.
 *
 * <h2>Two sources, both derived, neither typed</h2>
 * <ul>
 *   <li><b>Which genes are unverified</b> - every {@code wiki/gene-*.html} with
 *       no {@code id="verified"} anchor in it. The heading string is already a
 *       hard contract: {@link GeneWikiTool} carries that block across a rebake
 *       by searching for exactly it.</li>
 *   <li><b>What order</b> - the generated span of
 *       {@code wiki/timeline-of-genes.html}, which {@code bake-gene-timeline.mjs}
 *       writes newest-commit-first from git. Newest is worst: a painter written
 *       last week is where a drawing bug is, and one that has been on horses for
 *       a month has been seen by accident if not on purpose.</li>
 * </ul>
 *
 * <p>A page the timeline cannot date (its key never appears as a literal, so the
 * timeline lists it nowhere) is <b>appended alphabetically</b> rather than
 * dropped - being undateable is not the same as being verified.
 *
 * <p>Every unverified key is written, including genes that paint nothing and
 * genes this build does not register. {@code CoatCheckPlan} drops those at
 * runtime, which is what keeps a parked gene parked (hard rule 6's killswitch)
 * without this resource going stale every time the index changes.
 *
 * <p>Re-run whenever a {@code Verified} block is added or a gene page appears -
 * see the regenerate table in {@code CLAUDE.md}.
 */
public final class UnverifiedGeneTool {

    private static final String HEADER = ""
            + "# Genes whose wiki page carries no Verified block, worst-first.\n"
            + "# Generated by :common:bakeUnverifiedGenes - do not edit by hand.\n"
            + "# Newest by the gene timeline first; undateable pages last, alphabetically.\n";

    /**
     * A page saying somebody has looked at this gene in the game.
     *
     * <p><b>Two spellings, because there are two.</b> The current one is the
     * {@code id="verified"} anchor - a {@code <h3 id="verified">} heading or a
     * {@code <p id="verified-slug">} record - which {@link GeneWikiTool} treats
     * as a hard contract when it carries the block across a rebake. The older
     * one predates it and survives on the hand-written pages: a
     * {@code <div class="note good">} whose label reads "Owner-verified
     * in-game". Matching only the first counted agouti and champagne as
     * unconfirmed and would have filled the corridor with pens for work that was
     * done on 2026-09-01.
     */
    private static final Pattern VERIFIED = Pattern.compile("id=\"verified|Owner-verified in-game");

    private static final Pattern TIMELINE_HREF = Pattern.compile("href=\"(gene-[^\"]+\\.html)\"");

    private UnverifiedGeneTool() {
    }

    /**
     * @param args {@code <wiki dir> <output file>}
     */
    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            throw new IllegalArgumentException(
                    "usage: UnverifiedGeneTool <wiki dir> <output resource file>");
        }
        Path wiki = Path.of(args[0]);
        Path out = Path.of(args[1]);

        List<String> pages = unverifiedPages(wiki);
        List<String> ordered = inTimelineOrder(wiki, pages);

        StringBuilder sb = new StringBuilder(HEADER);
        for (String page : ordered) {
            sb.append(keyOf(page)).append('\n');
        }
        Files.createDirectories(out.getParent());
        Files.writeString(out, sb.toString(), StandardCharsets.UTF_8);

        System.out.println("Wrote " + out + " - " + ordered.size()
                + " unverified gene pages of " + countPages(wiki) + ".");
    }

    /** Every {@code gene-*.html} with no verified record anywhere in it. */
    private static List<String> unverifiedPages(Path wiki) throws IOException {
        List<String> out = new ArrayList<>();
        for (Path page : genePages(wiki)) {
            String src = Files.readString(page, StandardCharsets.UTF_8);
            if (!VERIFIED.matcher(src).find()) {
                out.add(page.getFileName().toString());
            }
        }
        return out;
    }

    private static List<Path> genePages(Path wiki) throws IOException {
        List<Path> out = new ArrayList<>();
        try (Stream<Path> stream = Files.list(wiki)) {
            for (Path p : (Iterable<Path>) stream::iterator) {
                String name = p.getFileName().toString();
                if (name.startsWith("gene-") && name.endsWith(".html")) {
                    out.add(p);
                }
            }
        }
        out.sort(null);
        return out;
    }

    private static int countPages(Path wiki) throws IOException {
        return genePages(wiki).size();
    }

    /**
     * {@code pages} sorted into the timeline's order, newest first, with
     * anything the timeline does not list appended alphabetically.
     */
    private static List<String> inTimelineOrder(Path wiki, List<String> pages) throws IOException {
        Set<String> wanted = new LinkedHashSet<>(pages);
        List<String> out = new ArrayList<>();

        Path timeline = wiki.resolve("timeline-of-genes.html");
        if (Files.exists(timeline)) {
            String src = Files.readString(timeline, StandardCharsets.UTF_8);
            int from = src.indexOf("BEGIN generated");
            int to = src.indexOf("END generated", Math.max(from, 0));
            if (from >= 0 && to > from) {
                Matcher m = TIMELINE_HREF.matcher(src.substring(from, to));
                while (m.find()) {
                    String href = m.group(1);
                    if (wanted.remove(href)) {
                        out.add(href);
                    }
                }
            } else {
                System.out.println("timeline-of-genes.html has no generated span - "
                        + "every gene will be listed alphabetically. Run bake-gene-timeline.mjs.");
            }
        }

        // Whatever the timeline never named: undateable, not verified.
        out.addAll(new TreeSet<>(wanted));
        if (!wanted.isEmpty()) {
            System.out.println("Not dated by the timeline, appended last: " + new TreeSet<>(wanted));
        }
        return out;
    }

    /**
     * {@code gene-molten-hooves.html} to {@code horsegenetics.molten_hooves} -
     * the inverse of {@code GeneWikiTool}'s page naming, which is the only place
     * the two conventions are allowed to differ from each other.
     */
    private static String keyOf(String page) {
        String slug = page.substring("gene-".length(), page.length() - ".html".length());
        return "horsegenetics." + slug.replace('-', '_').toLowerCase(Locale.ROOT);
    }
}
