package com.example.horsegenetics.common.coat;

import com.example.horsegenetics.common.genetics.Allele;
import com.example.horsegenetics.common.genetics.AllelePair;
import com.example.horsegenetics.common.genetics.Gene;
import com.example.horsegenetics.common.genetics.Genes;
import com.example.horsegenetics.common.genetics.Genotype;
import com.example.horsegenetics.common.genetics.Epigenome;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The regression guard for the "chestnut / bay horse renders as the plain white
 * template" bug: two different coats must never encode to the same texture id.
 * The old encoder lower-cased the key, which threw away the entire dominance
 * signal ({@code E} vs {@code e}, {@code W} vs {@code w}, ...).
 */
class CoatTextureIdTest {

    /**
     * Every genotype expressible with the registered genes - all
     * {@code 3^genes} of them, generated by index rather than materialized,
     * because that number is now 177 147 and grows by 3x per gene added.
     */
    private static void forEachGenotype(java.util.function.Consumer<Genotype> visitor) {
        List<Gene> genes = Genes.codeOrder();
        long total = genotypeCount();
        for (long i = 0; i < total; i++) {
            List<AllelePair> pairs = new ArrayList<>(genes.size());
            long rest = i;
            for (Gene g : genes) {
                List<Allele> as = g.alleles();
                Allele hi = as.get(0);
                Allele lo = as.get(as.size() - 1);
                pairs.add(switch ((int) (rest % 3)) {
                    case 0 -> new AllelePair(hi, hi);
                    case 1 -> new AllelePair(hi, lo);
                    default -> new AllelePair(lo, lo);
                });
                rest /= 3;
            }
            visitor.accept(Genotype.of(pairs));
        }
    }

    private static long genotypeCount() {
        long n = 1;
        for (int i = 0; i < Genes.codeOrder().size(); i++) {
            n *= 3;
        }
        return n;
    }

    /**
     * Injectivity, proved the cheap way: {@link CoatTextureId#decode} recovers
     * the key exactly, so two different keys cannot share an id. A map of every
     * id would be a million entries and is the same statement.
     */
    @Test
    void everyGenotypeGetsItsOwnTextureId() {
        long[] n = {0};
        forEachGenotype(g -> {
            for (long seed : new long[]{0L, 7L, -1L}) {
                for (String age : new String[]{":adult", ":foal"}) {
                    String key = new CoatData(g, Epigenome.fromSeed(seed)).textureKey() + age;
                    assertEquals(key, CoatTextureId.decode(CoatTextureId.encode(key)),
                            "id is not reversible, so two coats could collide on it: " + key);
                    n[0]++;
                }
            }
        });
        assertEquals(genotypeCount() * 3 * 2, n[0]);
        assertTrue(n[0] > 100_000, "expected every genotype x seed x age combination, got " + n[0]);
    }

    /** The same claim from the other side: no two genotypes land on one id. */
    @Test
    void noTwoGenotypesShareATextureId() {
        java.util.Set<String> ids = new java.util.HashSet<>();
        forEachGenotype(g -> {
            String id = CoatTextureId.encode(new CoatData(g, Epigenome.fromSeed(0L)).textureKey() + ":adult");
            assertTrue(ids.add(id), "texture id collision on " + id);
        });
        assertEquals(genotypeCount(), ids.size());
    }

    @Test
    void encodedIdsUseOnlyLegalResourcePathCharacters() {
        forEachGenotype(g -> {
            String id = CoatTextureId.encode(new CoatData(g, Epigenome.fromSeed(12345L)).textureKey() + ":adult");
            for (int i = 0; i < id.length(); i++) {
                char c = id.charAt(i);
                boolean legal = (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' || c == '.';
                assertTrue(legal, "illegal resource-path char '" + c + "' in " + id);
            }
        });
    }

    @Test
    void roundTrips() {
        for (String key : List.of(
                "E/e-A/a-w/w-t/t-c/c-spl/spl-g/g-Cr/N-N/N-n/n-n/n:adult",
                "e/e-a/a-W/W-T/t-Ch/c-Spl/spl-G/g-N/N-prl/N-n/n-n/n@18446744073709551615:foal",
                "",
                "..__@:/-")) {
            assertEquals(key, CoatTextureId.decode(CoatTextureId.encode(key)));
        }
    }

    @Test
    void dominanceSurvivesTheEncoding() {
        // the exact pair the old lower-casing encoder merged
        String white = Genotype.parse("E/E-A/A-W/W-t/t-c/c-spl/spl-g/g-N/N-N/N-n/n-n/n").toCode();
        String chestnut = Genotype.parse("e/e-a/a-w/w-t/t-c/c-spl/spl-g/g-N/N-N/N-n/n-n/n").toCode();
        assertEquals(white.toLowerCase(java.util.Locale.ROOT), chestnut.toLowerCase(java.util.Locale.ROOT));
        org.junit.jupiter.api.Assertions.assertNotEquals(
                CoatTextureId.encode(white), CoatTextureId.encode(chestnut));
    }
}
