package com.example.horsegenetics.neoforge.client;

import com.example.horsegenetics.neoforge.ClientConfig;
import com.example.horsegenetics.neoforge.server.DebugTestWorldHandler;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.TitleScreen;
import net.minecraft.network.chat.Component;
import net.minecraft.world.Difficulty;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.LevelSettings;
import net.minecraft.world.level.WorldDataConfiguration;
import net.minecraft.world.level.levelgen.WorldOptions;
import net.minecraft.world.level.levelgen.presets.WorldPresets;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ScreenEvent;

/**
 * Dev-only: a "Spawn Test Horse World" button on the title screen. It creates a
 * fresh throwaway world in <b>Creative</b> with cheats on, and flags
 * {@code DebugTestWorldHandler} to fill the hotbar (hay block, golden carrot,
 * stick, clock, paper, lead) on login - everything needed to exercise the
 * portal / taming / aging / inspect / lead features.
 *
 * <p>The world is throwaway: {@link DebugTestWorldCleanup} names the save
 * directory and deletes it again when the client shuts down.
 *
 * <h2>The seed is fixed, and it is fixed on purpose</h2>
 * It used to be {@code defaultWithRandomSeed()}, which meant every test world
 * was a different world: one session spent its first ten minutes swimming, the
 * next started in a ravine, and "the coat looks wrong" and "I am standing in a
 * dark forest at dusk" are hard to tell apart from a screenshot. A fixed seed
 * makes the ground itself a constant, so what changes between two runs is the
 * mod.
 *
 * <p>{@link #TEST_WORLD_SEED} drops you in <b>plains</b> - flat, bright, and
 * the biome horses spawn in, which is the one that matters here: a coat is read
 * against the ground it stands on, and a plains horse is the reference every
 * gene page's picture was judged against. The claim is checked rather than
 * trusted: {@code DebugTestWorldHandler} says on login which biome you actually
 * landed in and hands you a teleport if worldgen ever moves under it, and
 * {@code /testkit seed} prints it on demand.
 */
@EventBusSubscriber(value = Dist.CLIENT)
public final class DebugTitleScreenButton {

    /**
     * The seed every test world is generated from. <b>Verified, not guessed</b>:
     * fourteen candidates were each generated by a dedicated server and their
     * spawn biome read back out of the log, which is what
     * {@code DebugTestWorldHandler.onServerStarted} prints for.
     *
     * <p>This one spawns at {@code (-528, 69, 64)} in plains with <b>nine of
     * sixteen</b> points on a 64-block ring round it also plains - a field
     * rather than a pocket, which is the distinction that matters and the
     * reason the ring is sampled at all. Of the fourteen, three spawned in
     * plains and the other two were a shoreline pocket (three of sixteen) and a
     * fair one (six).
     *
     * <p>Changing it means re-verifying it the same way. The whole value of a
     * fixed seed is that a screenshot from one session and a screenshot from
     * the next are of the same place.
     */
    public static final long TEST_WORLD_SEED = 1234L;

    private DebugTitleScreenButton() {
    }

    @SubscribeEvent
    static void onTitleScreenInit(ScreenEvent.Init.Post event) {
        if (!ClientConfig.debugTools() || !(event.getScreen() instanceof TitleScreen)) {
            return;
        }
        Button button = Button.builder(
                        Component.literal("Spawn Test Horse World"),
                        b -> spawnTestHorseWorld())
                .bounds(4, 4, 168, 20)
                .build();
        event.addListener(button);
    }

    private static void spawnTestHorseWorld() {
        Minecraft mc = Minecraft.getInstance();
        String directory = DebugTestWorldCleanup.newDirectoryName();
        LevelSettings settings = new LevelSettings(
                "Test Horse World",
                GameType.CREATIVE,
                new LevelSettings.DifficultySettings(Difficulty.NORMAL, false, false),
                true, // allow cheats
                WorldDataConfiguration.DEFAULT);

        DebugTestWorldHandler.pendingHotbarFill = true;
        mc.createWorldOpenFlows().createFreshLevel(
                directory,
                settings,
                // Fixed seed, structures on, no bonus chest - the same three
                // things `runServer` generates from, which is what lets the seed
                // be checked without a client.
                new WorldOptions(TEST_WORLD_SEED, true, false),
                WorldPresets::createNormalWorldDimensions,
                mc.screen);
    }
}
