// SPIKE (2026-09-06): can TeaVM compile common/ to JavaScript?
//
// The question this module exists to answer is narrow: the horse designer is
// hosted on GitHub Pages, which is static, so there is no server to run the
// real coat pipeline on - and hand-porting genes to JavaScript is the thing we
// are trying to stop doing. TeaVM compiles JVM *bytecode*, so it is not a
// rewrite: it is common/ itself, running in the browser.
//
// common/ is an unusually good candidate - Java 17, zero third-party
// dependencies, no reflection anywhere in the coat pipeline, and
// CoatTextureComposer.compose takes int[] and returns int[], so nothing has to
// cross the boundary but numbers.
plugins {
    id("java")
    id("org.teavm") version "0.15.0"
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        // TeaVM itself needs 17+; common/ targets 17.
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation(project(":common"))
}

teavm {
    // The WebAssembly-GC backend. Worth testing against JS because the coat
    // pipeline's hot loop is BodyNoise, whose hash is 64-bit integer maths -
    // native in wasm, emulated with pairs of 32-bit ints in JavaScript.
    wasmGC {
        mainClass.set("com.example.horsegenetics.web.DesignerApi")
        obfuscated.set(true)
        sourceMap.set(false)
    }

    js {
        mainClass.set("com.example.horsegenetics.web.DesignerApi")
        // What ships: minified, no source map. Flip both while debugging.
        obfuscated.set(true)
        sourceMap.set(false)
        optimization.set(org.teavm.gradle.api.OptimizationLevel.AGGRESSIVE)
    }
}

// Everything the horse designer page loads at runtime, put where GitHub Pages
// can serve it. Checked in and regenerated by this task, the same arrangement
// as the gene creator's textures.js and expected.json.
//
// The PNGs are copied UNMODIFIED, at full size. The creator downsamples the
// 500x500 gradient to 256 because a preview only has to look right; this page
// must be byte-exact with the game, so it gets the real chart.
//
// Note the designer cannot run from a file:// path - loading the wasm is a
// fetch, and a local file is its own opaque origin. Serve the repo (any static
// server will do) or use the published wiki.
val designerDir = rootProject.layout.projectDirectory.dir("wiki/horse-designer")

tasks.register<Copy>("bakeDesignerAssets") {
    group = "horsegenetics"
    description = "Copy the wasm build and the real coat assets into wiki/horse-designer/"
    dependsOn(tasks.named("generateWasmGC"), tasks.named("copyWasmGCRuntime"))

    into(designerDir)

    from(layout.buildDirectory.dir("generated/teavm/wasm-gc")) {
        include("web.wasm", "web.wasm-runtime.js")
        into("wasm")
    }
    from(project(":common").layout.projectDirectory.dir("src/main/resources/assets/horsegenetics/textures")) {
        include("coat/redblackgradient.png", "coat/lutbluepink.png")
        include("entity/horse/horse_white.png", "entity/horse/horse_white_baby.png")
        eachFile { path = "assets/" + name }
        includeEmptyDirs = false
    }
}
